// Code generated by cmd/uigen from vocab.json. DO NOT EDIT.

package kit

import base "pecheny.me/dopeuikit/ui"

// Node types, re-exported so app code imports one package.
type Doc = base.Doc
type Node = base.Node
type Item = base.Item
type Attr = base.Attr
type Element = base.Element
type TextNode = base.TextNode
type RunNode = base.RunNode
type Comment = base.Comment
type BlankLine = base.BlankLine
type Doctype = base.Doctype

// Builder leaves, re-exported.
var New = base.New
var Text = base.Text
var Line = base.Line
var Inline = base.Inline
var CommentNode = base.CommentNode
var Blank = base.Blank
var ID = base.ID
var Aria = base.Aria
var Data = base.Data

// Primitive constructors.

func Page(items ...Item) *Element {
	return base.New("page", items...)
}

func Topbar(items ...Item) *Element {
	return base.New("topbar", items...)
}

func Iconbtn(items ...Item) *Element {
	return base.New("iconbtn", items...)
}

func Iconlink(items ...Item) *Element {
	return base.New("iconlink", items...)
}

func Col(items ...Item) *Element {
	return base.New("col", items...)
}

func Row(items ...Item) *Element {
	return base.New("row", items...)
}

func Spacer(items ...Item) *Element {
	return base.New("spacer", items...)
}

func Section(items ...Item) *Element {
	return base.New("section", items...)
}

func Paragraph(items ...Item) *Element {
	return base.New("text", items...)
}

func Hint(items ...Item) *Element {
	return base.New("hint", items...)
}

func Subhead(items ...Item) *Element {
	return base.New("subhead", items...)
}

func Empty(items ...Item) *Element {
	return base.New("empty", items...)
}

func SectionLabel(items ...Item) *Element {
	return base.New("label", items...)
}

func Bigcode(items ...Item) *Element {
	return base.New("bigcode", items...)
}

func Message(items ...Item) *Element {
	return base.New("message", items...)
}

func Strong(items ...Item) *Element {
	return base.New("strong", items...)
}

func Code(items ...Item) *Element {
	return base.New("code", items...)
}

func Muted(items ...Item) *Element {
	return base.New("muted", items...)
}

func Form(items ...Item) *Element {
	return base.New("form", items...)
}

func Textfield(items ...Item) *Element {
	return base.New("textfield", items...)
}

func Password(items ...Item) *Element {
	return base.New("password", items...)
}

func Filefield(items ...Item) *Element {
	return base.New("filefield", items...)
}

func Hiddenfield(items ...Item) *Element {
	return base.New("hiddenfield", items...)
}

func Numfield(items ...Item) *Element {
	return base.New("numfield", items...)
}

func Colorfield(items ...Item) *Element {
	return base.New("colorfield", items...)
}

func Sliderrow(items ...Item) *Element {
	return base.New("sliderrow", items...)
}

func Checkbox(items ...Item) *Element {
	return base.New("checkbox", items...)
}

func Radio(items ...Item) *Element {
	return base.New("radio", items...)
}

func Selectfield(items ...Item) *Element {
	return base.New("selectfield", items...)
}

func Option(items ...Item) *Element {
	return base.New("option", items...)
}

func Editor(items ...Item) *Element {
	return base.New("editor", items...)
}

func Button(items ...Item) *Element {
	return base.New("button", items...)
}

func Field(items ...Item) *Element {
	return base.New("field", items...)
}

func Unreaddot(items ...Item) *Element {
	return base.New("unreaddot", items...)
}

func Modal(items ...Item) *Element {
	return base.New("modal", items...)
}

func Dialog(items ...Item) *Element {
	return base.New("dialog", items...)
}

func Tabs(items ...Item) *Element {
	return base.New("tabs", items...)
}

func Tab(items ...Item) *Element {
	return base.New("tab", items...)
}

func Tabpanel(items ...Item) *Element {
	return base.New("tabpanel", items...)
}

func Details(items ...Item) *Element {
	return base.New("details", items...)
}

func Summary(items ...Item) *Element {
	return base.New("summary", items...)
}

func Fieldset(items ...Item) *Element {
	return base.New("fieldset", items...)
}

func Datalist(items ...Item) *Element {
	return base.New("datalist", items...)
}

func List(items ...Item) *Element {
	return base.New("list", items...)
}

func Listrow(items ...Item) *Element {
	return base.New("listrow", items...)
}

func Listtitle(items ...Item) *Element {
	return base.New("listtitle", items...)
}

func Table(items ...Item) *Element {
	return base.New("table", items...)
}

func Trow(items ...Item) *Element {
	return base.New("trow", items...)
}

func Hcell(items ...Item) *Element {
	return base.New("hcell", items...)
}

func Cell(items ...Item) *Element {
	return base.New("cell", items...)
}

func Mount(items ...Item) *Element {
	return base.New("mount", items...)
}

// Prop constructors.

func Title(v string) Attr {
	return Attr{Name: "title", Value: v}
}

func Hidden() Attr {
	return Attr{Name: "hidden", Bare: true}
}

func Grow() Attr {
	return Attr{Name: "grow", Bare: true}
}

func Scripts(v string) Attr {
	return Attr{Name: "scripts", Value: v}
}

func Classicscripts(v string) Attr {
	return Attr{Name: "classicscripts", Value: v}
}

func Titleid(v string) Attr {
	return Attr{Name: "titleid", Value: v}
}

func Home(v string) Attr {
	return Attr{Name: "home", Value: v}
}

func Nosync() Attr {
	return Attr{Name: "nosync", Bare: true}
}

func Syncstate(v string) Attr {
	return Attr{Name: "syncstate", Value: v}
}

func Label(v string) Attr {
	return Attr{Name: "label", Value: v}
}

func Badgeid(v string) Attr {
	return Attr{Name: "badgeid", Value: v}
}

func Href(v string) Attr {
	return Attr{Name: "href", Value: v}
}

func Wrap() Attr {
	return Attr{Name: "wrap", Bare: true}
}

func For(v string) Attr {
	return Attr{Name: "for", Value: v}
}

func Autocomplete(v string) Attr {
	return Attr{Name: "autocomplete", Value: v}
}

func Method(v string) Attr {
	return Attr{Name: "method", Value: v}
}

func Action(v string) Attr {
	return Attr{Name: "action", Value: v}
}

func Name(v string) Attr {
	return Attr{Name: "name", Value: v}
}

func Placeholder(v string) Attr {
	return Attr{Name: "placeholder", Value: v}
}

func Spellcheck(v string) Attr {
	return Attr{Name: "spellcheck", Value: v}
}

func Autocapitalize(v string) Attr {
	return Attr{Name: "autocapitalize", Value: v}
}

func Autocorrect(v string) Attr {
	return Attr{Name: "autocorrect", Value: v}
}

func Required() Attr {
	return Attr{Name: "required", Bare: true}
}

func Autofocus() Attr {
	return Attr{Name: "autofocus", Bare: true}
}

func Value(v string) Attr {
	return Attr{Name: "value", Value: v}
}

func Maxlength(v string) Attr {
	return Attr{Name: "maxlength", Value: v}
}

func Minlength(v string) Attr {
	return Attr{Name: "minlength", Value: v}
}

func Inputmode(v string) Attr {
	return Attr{Name: "inputmode", Value: v}
}

func Pattern(v string) Attr {
	return Attr{Name: "pattern", Value: v}
}

func InputList(v string) Attr {
	return Attr{Name: "list", Value: v}
}

func Readonly() Attr {
	return Attr{Name: "readonly", Bare: true}
}

func Disabled() Attr {
	return Attr{Name: "disabled", Bare: true}
}

func Accept(v string) Attr {
	return Attr{Name: "accept", Value: v}
}

func Min(v string) Attr {
	return Attr{Name: "min", Value: v}
}

func Max(v string) Attr {
	return Attr{Name: "max", Value: v}
}

func Step(v string) Attr {
	return Attr{Name: "step", Value: v}
}

func Narrow() Attr {
	return Attr{Name: "narrow", Bare: true}
}

func Valueid(v string) Attr {
	return Attr{Name: "valueid", Value: v}
}

func SliderHint(v string) Attr {
	return Attr{Name: "hint", Value: v}
}

func Checked() Attr {
	return Attr{Name: "checked", Bare: true}
}

func Compact() Attr {
	return Attr{Name: "compact", Bare: true}
}

func Selected() Attr {
	return Attr{Name: "selected", Bare: true}
}

func Rows(v string) Attr {
	return Attr{Name: "rows", Value: v}
}

func Small() Attr {
	return Attr{Name: "small", Bare: true}
}

func Submit() Attr {
	return Attr{Name: "submit", Bare: true}
}

func Download() Attr {
	return Attr{Name: "download", Bare: true}
}

func Formaction(v string) Attr {
	return Attr{Name: "formaction", Value: v}
}

func Formnovalidate() Attr {
	return Attr{Name: "formnovalidate", Bare: true}
}

func Done(v string) Attr {
	return Attr{Name: "done", Value: v}
}

func Doneid(v string) Attr {
	return Attr{Name: "doneid", Value: v}
}

func Open() Attr {
	return Attr{Name: "open", Bare: true}
}

func View(v string) Attr {
	return Attr{Name: "view", Value: v}
}

func Scroll() Attr {
	return Attr{Name: "scroll", Bare: true}
}

// Enum value constants (each carries its prop name).

var AlignStart = Attr{Name: "align", Value: "start"}
var AlignCenter = Attr{Name: "align", Value: "center"}
var AlignEnd = Attr{Name: "align", Value: "end"}
var AlignStretch = Attr{Name: "align", Value: "stretch"}
var Primary = Attr{Name: "kind", Value: "primary"}
var Ghost = Attr{Name: "kind", Value: "ghost"}
var Danger = Attr{Name: "kind", Value: "danger"}
var Secondary = Attr{Name: "kind", Value: "secondary"}
var CheckPlain = Attr{Name: "kind", Value: "plain"}
var EditorPlain = Attr{Name: "kind", Value: "plain"}
var DirRow = Attr{Name: "dir", Value: "row"}
var DirCol = Attr{Name: "dir", Value: "col"}
var JustifyStart = Attr{Name: "justify", Value: "start"}
var JustifyCenter = Attr{Name: "justify", Value: "center"}
var JustifyEnd = Attr{Name: "justify", Value: "end"}
var JustifyBetween = Attr{Name: "justify", Value: "between"}
var ModalVarPlain = Attr{Name: "variant", Value: "plain"}
var ModalVarLists = Attr{Name: "variant", Value: "lists"}
var ModalVarSizes = Attr{Name: "variant", Value: "sizes"}
var ModalVarWide = Attr{Name: "variant", Value: "wide"}
var PageSheet = Attr{Name: "kind", Value: "sheet"}
var PageFull = Attr{Name: "kind", Value: "full"}
var SpaceNone = Attr{Name: "gap", Value: "none"}
var SpaceXS = Attr{Name: "gap", Value: "xs"}
var SpaceSM = Attr{Name: "gap", Value: "sm"}
var SpaceMD = Attr{Name: "gap", Value: "md"}
var SpaceLG = Attr{Name: "gap", Value: "lg"}
var SpaceXL = Attr{Name: "gap", Value: "xl"}
