// genkinds writes web/ts/cardkind_gen.ts from cardkind.All, so the browser and
// the server cannot drift on what a Card Kind does.
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strings"

	"xy/internal/cardkind"
)

func main() {
	if len(os.Args) != 2 {
		log.Fatal("usage: genkinds <path of cardkind_gen.ts>")
	}
	var b strings.Builder
	b.WriteString("// Code generated by internal/cardkind/genkinds from cardkind.All. DO NOT EDIT.\n\n")
	b.WriteString("// Every Card Kind and what it does, in the order the kind menu lists the\n")
	b.WriteString("// pickable ones. cardkind.ts is what reads it.\n")
	b.WriteString("export const KINDS = [\n")
	for _, k := range cardkind.All {
		row, err := json.Marshal(k)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Fprintf(&b, "  %s,\n", row)
	}
	b.WriteString("] as const;\n\n")
	b.WriteString("export type KindName = (typeof KINDS)[number][\"name\"];\n")
	if err := os.WriteFile(os.Args[1], []byte(b.String()), 0o644); err != nil {
		log.Fatal(err)
	}
}
