// icongen is the one writer of icon shapes in this repo. It reads the vendored
// Lucide files (icons/svg/*.svg) and emits them into every language that draws
// an icon:
//
//	-go     a Go file of the shape bodies, for the server-rendered pages
//	-vocab  the kit's vocab.json, whose `icon-name` enum it keeps in step
//	-ts     a TypeScript module with the same bodies (repeatable, one per app)
//
// The vocab is the point of the third output: with the names generated into the
// closed vocabulary, `button icon="trahs-2"` fails to compile instead of
// rendering an empty box.
//
// Run through `go generate ./icons` from dopeuikit/, and checked by the root
// justfile's generate-check.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type pathList []string

func (p *pathList) String() string     { return strings.Join(*p, ",") }
func (p *pathList) Set(v string) error { *p = append(*p, v); return nil }

// The <svg> wrapper is stripped: every consumer writes its own, so the vendored
// width/height/class never reach a page.
var svgOpen = regexp.MustCompile(`(?s)^.*?<svg[^>]*>`)

func main() {
	goPath := flag.String("go", "", "path for the generated Go bodies")
	vocabPath := flag.String("vocab", "", "vocab.json whose icon-name enum to regenerate")
	svgDir := flag.String("svg", "svg", "directory of vendored .svg files")
	var tsPaths pathList
	flag.Var(&tsPaths, "ts", "path for a generated TypeScript module (repeatable)")
	flag.Parse()

	entries, err := filepath.Glob(filepath.Join(*svgDir, "*.svg"))
	must(err)
	if len(entries) == 0 {
		fatal(fmt.Errorf("no .svg files in %s", *svgDir))
	}
	bodies := map[string]string{}
	for _, f := range entries {
		raw, err := os.ReadFile(f)
		must(err)
		body := svgOpen.ReplaceAllString(string(raw), "")
		body = strings.TrimSpace(strings.TrimSuffix(strings.TrimSpace(body), "</svg>"))
		// One line: the markup is inlined into a page, and a shape's internal
		// newlines are noise in every output.
		body = strings.Join(strings.Fields(body), " ")
		if body == "" {
			fatal(fmt.Errorf("%s: empty after stripping the <svg> wrapper", f))
		}
		bodies[strings.TrimSuffix(filepath.Base(f), ".svg")] = body
	}
	names := make([]string, 0, len(bodies))
	for n := range bodies {
		names = append(names, n)
	}
	sort.Strings(names)

	if *goPath != "" {
		must(os.WriteFile(*goPath, []byte(renderGo(names, bodies)), 0o644))
	}
	for _, p := range tsPaths {
		must(os.WriteFile(p, []byte(renderTS(names, bodies)), 0o644))
	}
	if *vocabPath != "" {
		must(patchVocab(*vocabPath, names))
	}
	fmt.Printf("icongen: %d icons\n", len(names))
}

const banner = "// Code generated by cmd/icongen from icons/svg/*.svg. DO NOT EDIT.\n" +
	"// Shapes are Lucide (lucide.dev), ISC — see icons/LICENSE.lucide.\n"

func renderGo(names []string, bodies map[string]string) string {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("\npackage icons\n\nvar bodies = map[string]string{\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\t%q: %q,\n", n, bodies[n])
	}
	b.WriteString("}\n")
	return b.String()
}

func renderTS(names []string, bodies map[string]string) string {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString(`
// The browser half of the icon set: buttons built in TypeScript draw the same
// shapes the compiled pages do. icon() returns a fresh element each call — an
// SVG node has one parent, so a shared instance would teleport between buttons.

export type IconName =
`)
	for i, n := range names {
		sep := "  | "
		if i == 0 {
			sep = "    "
		}
		fmt.Fprintf(&b, "%s%q\n", sep, n)
	}
	b.WriteString(";\n\nconst BODIES: Record<IconName, string> = {\n")
	for _, n := range names {
		fmt.Fprintf(&b, "  %q: %q,\n", n, bodies[n])
	}
	b.WriteString(`};

const NS = "http://www.w3.org/2000/svg";

// icon builds one 24px Lucide glyph stroked in currentColor, so it is coloured
// by the button's own text rule and follows the theme.
export function icon(name: IconName): SVGSVGElement {
  const svg = document.createElementNS(NS, "svg");
  svg.setAttribute("class", "ico");
  svg.setAttribute("viewBox", "0 0 24 24");
  svg.setAttribute("fill", "none");
  svg.setAttribute("stroke", "currentColor");
  svg.setAttribute("stroke-width", "2");
  svg.setAttribute("stroke-linecap", "round");
  svg.setAttribute("stroke-linejoin", "round");
  svg.setAttribute("aria-hidden", "true");
  // The bodies are generated from files in this repo, never from user input.
  svg.innerHTML = BODIES[name];
  return svg;
}

// iconed builds the common shape of a labelled control: the glyph, then the
// words. Menu rows keep their text — a dropdown is read by its label, and the
// glyph is only an anchor for the eye.
export function iconed(name: IconName, label: string): (SVGSVGElement | string)[] {
  return [icon(name), label];
}
`)
	return b.String()
}

// patchVocab rewrites the icon-name enum in place. It splices text rather than
// re-marshalling the document: vocab.json is hand-authored and hand-formatted,
// and only this one list is generated.
func patchVocab(path string, names []string) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("    \"icon-name\": {\n      \"prefix\": \"Icon\",\n      \"values\": [\n")
	for i, n := range names {
		comma := ","
		if i == len(names)-1 {
			comma = ""
		}
		fmt.Fprintf(&b, "        %q%s\n", n, comma)
	}
	b.WriteString("      ]\n    }")
	block := b.String()

	existing := regexp.MustCompile(`(?s)    "icon-name": \{.*?\n    \}`)
	var out string
	switch {
	case existing.Match(raw):
		out = existing.ReplaceAllLiteralString(string(raw), block)
	default:
		// First run: open the enums object with it.
		const anchor = "  \"enums\": {\n"
		i := strings.Index(string(raw), anchor)
		if i < 0 {
			return fmt.Errorf("%s: no \"enums\" object to add icon-name to", path)
		}
		at := i + len(anchor)
		out = string(raw)[:at] + block + ",\n" + string(raw)[at:]
	}
	// The result must still parse: a bad splice is a broken build everywhere.
	if !json.Valid([]byte(out)) {
		return fmt.Errorf("%s: splice produced invalid JSON", path)
	}
	return os.WriteFile(path, []byte(out), 0o644)
}

func must(err error) {
	if err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "icongen:", err)
	os.Exit(1)
}
