// Code generated by scripts/i18nstringsgen from i18nstrings/en/*.toml. DO NOT EDIT.

package i18nstrings

import (
	"fmt"

	core "pecheny.me/dopecore/i18nstrings"
)

// EN is the en Catalog.
var EN = Strings{
	Board: BoardStrings{
		Delete: BoardDeleteStrings{
			Confirm: func(title string, cards int) string {
				return fmt.Sprintf("Delete board %s? It holds %s — %d.", title, core.Plural("en", cards, "card", "cards", "cards"), cards)
			},
			Percent: func() string { return "100% done" },
			Title:   func() string { return "Deleting a board" },
		},
	},
	Common: CommonStrings{
		Save: func() string { return "Save" },
		Selection: CommonSelectionStrings{
			Count: func(n int) string {
				return fmt.Sprintf("Selected %d %s", n, core.Plural("en", n, "item", "items", "items"))
			},
		},
	},
}
