// Code generated by scripts/i18nstringsgen from i18nstrings/*/*.toml. DO NOT EDIT.

/** One language's Catalog: a key per Surface, a nested object per group,
 * a function per string. */
export type Strings = {
  board: {
    delete: {
      confirm: (title: string, cards: number) => string;
      percent: () => string;
      title: () => string;
    };
  };
  common: {
    save: () => string;
    selection: {
      count: (n: number) => string;
    };
  };
};
