// Code generated by scripts/i18nstringsgen from i18nstrings/en/*.toml. DO NOT EDIT.

import { plural } from "./i18nstrings_plural_gen.js";
import type { Strings } from "./i18nstrings_types_gen.js";

export const EN: Strings = {
  board: {
    delete: {
      confirm: (title: string, cards: number) => `Delete board ${title}? It holds ${plural("en", cards, "card", "cards", "cards")} — ${cards}.`,
      percent: () => "100% done",
      title: () => "Deleting a board",
    },
  },
  common: {
    save: () => "Save",
    selection: {
      count: (n: number) => `Selected ${n} ${plural("en", n, "item", "items", "items")}`,
    },
  },
};

export default EN;
