// Code generated by scripts/i18nstringsgen from i18nstrings/ru/*.toml. DO NOT EDIT.

import { plural } from "./i18nstrings_plural_gen.js";
import type { Strings } from "./i18nstrings_types_gen.js";

export const RU: Strings = {
  board: {
    delete: {
      confirm: (title: string, cards: number) => `Удалить доску ${title}? В ней ${plural("ru", cards, "карточка", "карточки", "карточек")} — ${cards}.`,
      percent: () => "Готово на 100%",
      title: () => "Удаление доски",
    },
  },
  common: {
    save: () => "Сохранить",
    selection: {
      count: (n: number) => `Выбрано ${n} ${plural("ru", n, "элемент", "элемента", "элементов")}`,
    },
  },
};

export default RU;
