// Code generated by scripts/i18nstringsgen from i18nstrings/ru/*.toml. DO NOT EDIT.

package i18nstrings

import (
	"fmt"

	core "pecheny.me/dopecore/i18nstrings"
)

// RU is the ru Catalog.
var RU = Strings{
	Board: BoardStrings{
		Delete: BoardDeleteStrings{
			Confirm: func(title string, cards int) string {
				return fmt.Sprintf("Удалить доску %s? В ней %s — %d.", title, core.Plural("ru", cards, "карточка", "карточки", "карточек"), cards)
			},
			Percent: func() string { return "Готово на 100%" },
			Title:   func() string { return "Удаление доски" },
		},
	},
	Common: CommonStrings{
		Save: func() string { return "Сохранить" },
		Selection: CommonSelectionStrings{
			Count: func(n int) string {
				return fmt.Sprintf("Выбрано %d %s", n, core.Plural("ru", n, "элемент", "элемента", "элементов"))
			},
		},
	},
}
