// Code generated by scripts/i18nstringsgen from i18nstrings/*/*.toml. DO NOT EDIT.

package i18nstrings

// Strings is one language's Catalog: a field per Surface, a nested struct
// per group, a func per string.
type Strings struct {
	Board  BoardStrings
	Common CommonStrings
}

// BoardStrings is the board Surface.
type BoardStrings struct {
	Delete BoardDeleteStrings
}

type BoardDeleteStrings struct {
	Confirm func(title string, cards int) string
	Percent func() string
	Title   func() string
}

// CommonStrings is the common Surface.
type CommonStrings struct {
	Save      func() string
	Selection CommonSelectionStrings
}

type CommonSelectionStrings struct {
	Count func(n int) string
}

// Lookup returns an untemplated string by its String Id, for `@surface.key`
// in a .dopeui page.
func (s Strings) Lookup(id string) (string, bool) {
	switch id {
	case "board.delete.percent":
		return s.Board.Delete.Percent(), true
	case "board.delete.title":
		return s.Board.Delete.Title(), true
	case "common.save":
		return s.Common.Save(), true
	}
	return "", false
}

// Defines reports whether the Catalog holds the id at all, templated or not.
func (Strings) Defines(id string) bool {
	switch id {
	case "board.delete.confirm", "board.delete.percent", "board.delete.title", "common.save", "common.selection.count":
		return true
	}
	return false
}
