// Code generated by cmd/uigen from vocab.json. DO NOT EDIT.

package ui

import base "pecheny.me/dopeuikit/kit"

// Node types, re-exported so app code imports one package.
type Doc = base.Doc
type Node = base.Node
type Item = base.Item
type Attr = base.Attr
type Element = base.Element
type TextNode = base.TextNode
type RunNode = base.RunNode
type Comment = base.Comment
type BlankLine = base.BlankLine
type Doctype = base.Doctype

// Builder leaves, re-exported.
var New = base.New
var Text = base.Text
var Line = base.Line
var Inline = base.Inline
var CommentNode = base.CommentNode
var Blank = base.Blank
var ID = base.ID
var Aria = base.Aria
var Data = base.Data

// Base primitive constructors, re-exported.
var Page = base.Page
var Topbar = base.Topbar
var Iconbtn = base.Iconbtn
var Iconlink = base.Iconlink
var Col = base.Col
var Row = base.Row
var Spacer = base.Spacer
var Section = base.Section
var Paragraph = base.Paragraph
var Hint = base.Hint
var Subhead = base.Subhead
var Empty = base.Empty
var SectionLabel = base.SectionLabel
var Bigcode = base.Bigcode
var Message = base.Message
var Strong = base.Strong
var Code = base.Code
var Muted = base.Muted
var Form = base.Form
var Textfield = base.Textfield
var Password = base.Password
var Filefield = base.Filefield
var Hiddenfield = base.Hiddenfield
var Numfield = base.Numfield
var Colorfield = base.Colorfield
var Sliderrow = base.Sliderrow
var Checkbox = base.Checkbox
var Radio = base.Radio
var Selectfield = base.Selectfield
var Option = base.Option
var Editor = base.Editor
var Button = base.Button
var Field = base.Field
var Unreaddot = base.Unreaddot
var Modal = base.Modal
var Dialog = base.Dialog
var Tabs = base.Tabs
var Tab = base.Tab
var Tabpanel = base.Tabpanel
var Details = base.Details
var Summary = base.Summary
var Fieldset = base.Fieldset
var Datalist = base.Datalist
var List = base.List
var Listrow = base.Listrow
var Listtitle = base.Listtitle
var Table = base.Table
var Trow = base.Trow
var Hcell = base.Hcell
var Cell = base.Cell
var Mount = base.Mount

// Base prop constructors, re-exported.
var Title = base.Title
var Hidden = base.Hidden
var Grow = base.Grow
var Scripts = base.Scripts
var Classicscripts = base.Classicscripts
var Titleid = base.Titleid
var Home = base.Home
var Nosync = base.Nosync
var Syncstate = base.Syncstate
var Label = base.Label
var Badgeid = base.Badgeid
var Href = base.Href
var Wrap = base.Wrap
var For = base.For
var Autocomplete = base.Autocomplete
var Method = base.Method
var Action = base.Action
var Name = base.Name
var Placeholder = base.Placeholder
var Spellcheck = base.Spellcheck
var Autocapitalize = base.Autocapitalize
var Autocorrect = base.Autocorrect
var Required = base.Required
var Autofocus = base.Autofocus
var Value = base.Value
var Maxlength = base.Maxlength
var Minlength = base.Minlength
var Inputmode = base.Inputmode
var Pattern = base.Pattern
var InputList = base.InputList
var Readonly = base.Readonly
var Disabled = base.Disabled
var Accept = base.Accept
var Min = base.Min
var Max = base.Max
var Step = base.Step
var Narrow = base.Narrow
var Valueid = base.Valueid
var SliderHint = base.SliderHint
var Checked = base.Checked
var Compact = base.Compact
var Selected = base.Selected
var Rows = base.Rows
var Small = base.Small
var Submit = base.Submit
var Download = base.Download
var Formaction = base.Formaction
var Formnovalidate = base.Formnovalidate
var Done = base.Done
var Doneid = base.Doneid
var Open = base.Open
var View = base.View
var Scroll = base.Scroll

// Base enum constants, re-exported.
var AlignStart = base.AlignStart
var AlignCenter = base.AlignCenter
var AlignEnd = base.AlignEnd
var AlignStretch = base.AlignStretch
var Primary = base.Primary
var Ghost = base.Ghost
var Danger = base.Danger
var Secondary = base.Secondary
var CheckPlain = base.CheckPlain
var EditorPlain = base.EditorPlain
var DirRow = base.DirRow
var DirCol = base.DirCol
var JustifyStart = base.JustifyStart
var JustifyCenter = base.JustifyCenter
var JustifyEnd = base.JustifyEnd
var JustifyBetween = base.JustifyBetween
var ModalVarPlain = base.ModalVarPlain
var ModalVarLists = base.ModalVarLists
var ModalVarSizes = base.ModalVarSizes
var PageSheet = base.PageSheet
var PageFull = base.PageFull
var SpaceNone = base.SpaceNone
var SpaceXS = base.SpaceXS
var SpaceSM = base.SpaceSM
var SpaceMD = base.SpaceMD
var SpaceLG = base.SpaceLG
var SpaceXL = base.SpaceXL

// Primitive constructors.

func Previewtitle(items ...Item) *Element {
	return base.New("previewtitle", items...)
}

func Docoverlay(items ...Item) *Element {
	return base.New("docoverlay", items...)
}

func Headrow(items ...Item) *Element {
	return base.New("headrow", items...)
}

func Headactions(items ...Item) *Element {
	return base.New("headactions", items...)
}

func Split(items ...Item) *Element {
	return base.New("split", items...)
}

func Pane(items ...Item) *Element {
	return base.New("pane", items...)
}

// Enum value constants (each carries its prop name).

var CheckPreview = Attr{Name: "kind", Value: "preview"}
var CheckCardPreview = Attr{Name: "kind", Value: "card-preview"}
var DocKindDoc = Attr{Name: "kind", Value: "doc"}
var DocKindDetail = Attr{Name: "kind", Value: "detail"}
var DocVarPlain = Attr{Name: "variant", Value: "plain"}
var DocVarHandouts = Attr{Name: "variant", Value: "handouts"}
var DocVarImport = Attr{Name: "variant", Value: "import"}
var EditorComment = Attr{Name: "kind", Value: "comment"}
var EditorHandouts = Attr{Name: "kind", Value: "handouts"}
var EditorImportsrc = Attr{Name: "kind", Value: "importsrc"}
var HeadDoc = Attr{Name: "kind", Value: "doc"}
var HeadDetail = Attr{Name: "kind", Value: "detail"}
var MountKanban = Attr{Name: "kind", Value: "kanban"}
var MountBoardGrid = Attr{Name: "kind", Value: "board-grid"}
var MountTimeline = Attr{Name: "kind", Value: "timeline"}
var MountLabelPicker = Attr{Name: "kind", Value: "label-picker"}
var MountLabelAddRow = Attr{Name: "kind", Value: "label-add-row"}
var MountAttachments = Attr{Name: "kind", Value: "attachments"}
var MountCardFields = Attr{Name: "kind", Value: "card-fields"}
var MountPreviewBody = Attr{Name: "kind", Value: "preview-body"}
var MountCardPreviewBody = Attr{Name: "kind", Value: "card-preview-body"}
var MountHandoutsPdf = Attr{Name: "kind", Value: "handouts-pdf"}
var MountImportPreview = Attr{Name: "kind", Value: "import-preview"}
var MountListsManageRows = Attr{Name: "kind", Value: "lists-manage-rows"}
var MountMembersList = Attr{Name: "kind", Value: "members-list"}
var MountTokenList = Attr{Name: "kind", Value: "token-list"}
var MountTokenValue = Attr{Name: "kind", Value: "token-value"}
var MountCardCopyMsg = Attr{Name: "kind", Value: "card-copy-msg"}
var MountImportCount = Attr{Name: "kind", Value: "import-count"}
var MountCardTitle = Attr{Name: "kind", Value: "card-title"}
var PageWide = Attr{Name: "kind", Value: "wide"}
var PageBoard = Attr{Name: "kind", Value: "board"}
var PaneSrc = Attr{Name: "kind", Value: "src"}
var PanePreview = Attr{Name: "kind", Value: "preview"}
