// Code generated by cmd/uigen from vocab.json. DO NOT EDIT.

package ui

// Element constructors.

func Html(items ...Item) *Element {
	return newElement("html", items)
}

func Head(items ...Item) *Element {
	return newElement("head", items)
}

func Meta(items ...Item) *Element {
	return newElement("meta", items)
}

func Title(items ...Item) *Element {
	return newElement("title", items)
}

func Link(items ...Item) *Element {
	return newElement("link", items)
}

func Script(items ...Item) *Element {
	return newElement("script", items)
}

func Body(items ...Item) *Element {
	return newElement("body", items)
}

func Header(items ...Item) *Element {
	return newElement("header", items)
}

func H1(items ...Item) *Element {
	return newElement("h1", items)
}

func H2(items ...Item) *Element {
	return newElement("h2", items)
}

func H3(items ...Item) *Element {
	return newElement("h3", items)
}

func Div(items ...Item) *Element {
	return newElement("div", items)
}

func Span(items ...Item) *Element {
	return newElement("span", items)
}

func A(items ...Item) *Element {
	return newElement("a", items)
}

func Main(items ...Item) *Element {
	return newElement("main", items)
}

func Section(items ...Item) *Element {
	return newElement("section", items)
}

func P(items ...Item) *Element {
	return newElement("p", items)
}

func Strong(items ...Item) *Element {
	return newElement("strong", items)
}

func Form(items ...Item) *Element {
	return newElement("form", items)
}

func Input(items ...Item) *Element {
	return newElement("input", items)
}

func Button(items ...Item) *Element {
	return newElement("button", items)
}

func Pre(items ...Item) *Element {
	return newElement("pre", items)
}

func Label(items ...Item) *Element {
	return newElement("label", items)
}

func Select(items ...Item) *Element {
	return newElement("select", items)
}

func Option(items ...Item) *Element {
	return newElement("option", items)
}

func Textarea(items ...Item) *Element {
	return newElement("textarea", items)
}

func Ul(items ...Item) *Element {
	return newElement("ul", items)
}

func Li(items ...Item) *Element {
	return newElement("li", items)
}

func Code(items ...Item) *Element {
	return newElement("code", items)
}

func Table(items ...Item) *Element {
	return newElement("table", items)
}

func Thead(items ...Item) *Element {
	return newElement("thead", items)
}

func Tbody(items ...Item) *Element {
	return newElement("tbody", items)
}

func Tr(items ...Item) *Element {
	return newElement("tr", items)
}

func Th(items ...Item) *Element {
	return newElement("th", items)
}

func Td(items ...Item) *Element {
	return newElement("td", items)
}

// Attribute constructors.

func Lang(v string) Attr {
	return Attr{Name: "lang", Value: v}
}

func Charset(v string) Attr {
	return Attr{Name: "charset", Value: v}
}

func Name(v string) Attr {
	return Attr{Name: "name", Value: v}
}

func Content(v string) Attr {
	return Attr{Name: "content", Value: v}
}

func Rel(v string) Attr {
	return Attr{Name: "rel", Value: v}
}

func Href(v string) Attr {
	return Attr{Name: "href", Value: v}
}

func As(v string) Attr {
	return Attr{Name: "as", Value: v}
}

func Type(v string) Attr {
	return Attr{Name: "type", Value: v}
}

func Crossorigin() Attr {
	return Attr{Name: "crossorigin", Bare: true}
}

func Src(v string) Attr {
	return Attr{Name: "src", Value: v}
}

func Defer() Attr {
	return Attr{Name: "defer", Bare: true}
}

func Method(v string) Attr {
	return Attr{Name: "method", Value: v}
}

func Action(v string) Attr {
	return Attr{Name: "action", Value: v}
}

func Autocomplete(v string) Attr {
	return Attr{Name: "autocomplete", Value: v}
}

func Placeholder(v string) Attr {
	return Attr{Name: "placeholder", Value: v}
}

func Spellcheck(v string) Attr {
	return Attr{Name: "spellcheck", Value: v}
}

func Autocapitalize(v string) Attr {
	return Attr{Name: "autocapitalize", Value: v}
}

func Autocorrect(v string) Attr {
	return Attr{Name: "autocorrect", Value: v}
}

func Required() Attr {
	return Attr{Name: "required", Bare: true}
}

func Autofocus() Attr {
	return Attr{Name: "autofocus", Bare: true}
}

func Value(v string) Attr {
	return Attr{Name: "value", Value: v}
}

func Checked() Attr {
	return Attr{Name: "checked", Bare: true}
}

func Min(v string) Attr {
	return Attr{Name: "min", Value: v}
}

func Maxlength(v string) Attr {
	return Attr{Name: "maxlength", Value: v}
}

func Accept(v string) Attr {
	return Attr{Name: "accept", Value: v}
}

func Disabled() Attr {
	return Attr{Name: "disabled", Bare: true}
}

func For(v string) Attr {
	return Attr{Name: "for", Value: v}
}

func Download() Attr {
	return Attr{Name: "download", Bare: true}
}

func Rows(v string) Attr {
	return Attr{Name: "rows", Value: v}
}

func Readonly() Attr {
	return Attr{Name: "readonly", Bare: true}
}

func TitleAttr(v string) Attr {
	return Attr{Name: "title", Value: v}
}

func Hidden() Attr {
	return Attr{Name: "hidden", Bare: true}
}

func Role(v string) Attr {
	return Attr{Name: "role", Value: v}
}

// ClassToken constants: the closed class-token whitelist (type declared in builder.go).

const ActionIcon ClassToken = "action-icon"
const AppearanceModal ClassToken = "appearance-modal"
const AppearanceModalDone ClassToken = "appearance-modal-done"
const AppearanceModalOverlay ClassToken = "appearance-modal-overlay"
const AppearanceModalTitle ClassToken = "appearance-modal-title"
const AttachAdd ClassToken = "attach-add"
const AttachLossless ClassToken = "attach-lossless"
const Attachments ClassToken = "attachments"
const AuthActions ClassToken = "auth-actions"
const AuthForm ClassToken = "auth-form"
const AuthFormStack ClassToken = "auth-form-stack"
const AuthHint ClassToken = "auth-hint"
const AuthStep ClassToken = "auth-step"
const AuthSubhead ClassToken = "auth-subhead"
const BoardGrid ClassToken = "board-grid"
const BoardMain ClassToken = "board-main"
const BoardPage ClassToken = "board-page"
const Btn ClassToken = "btn"
const BtnGhost ClassToken = "btn-ghost"
const BtnSmall ClassToken = "btn-small"
const Card ClassToken = "card"
const CardCopyMsg ClassToken = "card-copy-msg"
const CardDesc ClassToken = "card-desc"
const CardDetail ClassToken = "card-detail"
const CardDetailHead ClassToken = "card-detail-head"
const CardDetailTitle ClassToken = "card-detail-title"
const CardFields ClassToken = "card-fields"
const CardHeadActions ClassToken = "card-head-actions"
const CardKindSelect ClassToken = "card-kind-select"
const CardMove ClassToken = "card-move"
const CardMoveActions ClassToken = "card-move-actions"
const CardMoveStack ClassToken = "card-move-stack"
const CardOverlay ClassToken = "card-overlay"
const CardPreviewBody ClassToken = "card-preview-body"
const CardPreviewScreen ClassToken = "card-preview-screen"
const CardSectionLabel ClassToken = "card-section-label"
const CardView ClassToken = "card-view"
const CardViewTab ClassToken = "card-view-tab"
const CardViewTabs ClassToken = "card-view-tabs"
const Cluster ClassToken = "cluster"
const CommentForm ClassToken = "comment-form"
const CommentInput ClassToken = "comment-input"
const DataTable ClassToken = "data-table"
const Empty ClassToken = "empty"
const Field ClassToken = "field"
const HandoutsBody ClassToken = "handouts-body"
const HandoutsDoc ClassToken = "handouts-doc"
const HandoutsPane ClassToken = "handouts-pane"
const HandoutsPdf ClassToken = "handouts-pdf"
const HandoutsPreview ClassToken = "handouts-preview"
const HandoutsPreviewHead ClassToken = "handouts-preview-head"
const HandoutsSrc ClassToken = "handouts-src"
const HandoutsTextarea ClassToken = "handouts-textarea"
const Host ClassToken = "host"
const HostActions ClassToken = "host-actions"
const HostBrand ClassToken = "host-brand"
const HostHome ClassToken = "host-home"
const HostSep ClassToken = "host-sep"
const HostTitle ClassToken = "host-title"
const HostTop ClassToken = "host-top"
const ImportForm ClassToken = "import-form"
const ImportFrame ClassToken = "import-frame"
const ImportMessage ClassToken = "import-message"
const ImportPage ClassToken = "import-page"
const InputClass ClassToken = "input"
const Kanban ClassToken = "kanban"
const LabelAddBtn ClassToken = "label-add-btn"
const LabelAddRow ClassToken = "label-add-row"
const LabelColorInput ClassToken = "label-color-input"
const LabelCreate ClassToken = "label-create"
const LabelPicker ClassToken = "label-picker"
const List ClassToken = "list"
const ListRow ClassToken = "list-row"
const ListRowTitle ClassToken = "list-row-title"
const ListsManage ClassToken = "lists-manage"
const ListsManageMoverow ClassToken = "lists-manage-moverow"
const ListsManageRows ClassToken = "lists-manage-rows"
const ListsManageToolbar ClassToken = "lists-manage-toolbar"
const ListsMovePos ClassToken = "lists-move-pos"
const MatchMain ClassToken = "match-main"
const MemberAdd ClassToken = "member-add"
const MembersList ClassToken = "members-list"
const Muted ClassToken = "muted"
const NotifBadge ClassToken = "notif-badge"
const NotifToggle ClassToken = "notif-toggle"
const PreviewBody ClassToken = "preview-body"
const PreviewDoc ClassToken = "preview-doc"
const PreviewHead ClassToken = "preview-head"
const PreviewHeadActions ClassToken = "preview-head-actions"
const PreviewOverlay ClassToken = "preview-overlay"
const PreviewScreenToggle ClassToken = "preview-screen-toggle"
const PreviewTitle ClassToken = "preview-title"
const Public ClassToken = "public"
const PublicMain ClassToken = "public-main"
const PublicTop ClassToken = "public-top"
const PublicUser ClassToken = "public-user"
const RegisterCode ClassToken = "register-code"
const SectionClass ClassToken = "section"
const SheetFrame ClassToken = "sheet-frame"
const Stack ClassToken = "stack"
const SyncStatus ClassToken = "sync-status"
const Timeline ClassToken = "timeline"
const TokenList ClassToken = "token-list"
const TokenReveal ClassToken = "token-reveal"
const TokenValue ClassToken = "token-value"
const UnreadDot ClassToken = "unread-dot"
