// Code generated by scripts/i18nstringsgen from i18nstrings/ru/*.toml. DO NOT EDIT.

package i18nstrings

import (
	"fmt"

	core "pecheny.me/dopecore/i18nstrings"
)

// RU is the ru Catalog.
var RU = Strings{
	Common: CommonStrings{
		Cancel: func() string { return "Отмена" },
		Save:   func() string { return "Сохранить" },
		Selection: CommonSelectionStrings{
			Count: func(n int) string {
				return fmt.Sprintf("Выбрано %d %s", n, core.Plural("ru", n, "элемент", "элемента", "элементов"))
			},
		},
	},
}
