// Code generated by scripts/i18nstringsgen from i18nstrings/*/*.toml. DO NOT EDIT.

package i18nstrings

// Strings is one language's Catalog: a field per Surface, a nested struct
// per group, a func per string.
type Strings struct {
	Common CommonStrings
}

// CommonStrings is the common Surface.
type CommonStrings struct {
	Cancel    func() string
	Save      func() string
	Selection CommonSelectionStrings
}

type CommonSelectionStrings struct {
	Count func(n int) string
}
