// palettegen is the one writer of colour in this repo. It reads the vendored
// uchu ramps (palette/uchu.json) and the app colour sets (palette/sets.json) and
// emits them into every language that needs them:
//
//	-css   a named GENERATED region in a stylesheet (repeatable)
//	-go    a Go file of the sets, for the server-rendered swatch enums
//	-ts    a TypeScript module of the sets, for the browser pickers
//
// The sticker palette used to live in three of those at once — a Go enum, a CSS
// custom-property block, and a comment asking a human to keep the two in sync.
// That comment is what this command replaces.
//
// Run through `go generate ./palette` from dopeuikit/, and checked by the root
// justfile's generate-check.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"pecheny.me/dopeuikit/palette"
)

type pathList []string

func (p *pathList) String() string     { return strings.Join(*p, ",") }
func (p *pathList) Set(v string) error { *p = append(*p, v); return nil }

func main() {
	var cssPaths pathList
	flag.Var(&cssPaths, "css", "stylesheet with GENERATED regions to fill (repeatable)")
	goPath := flag.String("go", "", "path for the generated Go sets")
	tsPath := flag.String("ts", "", "path for the generated TypeScript sets")
	tsSetNames := flag.String("ts-sets", "", "comma-separated sets to emit to TypeScript (default: all)")
	flag.Parse()

	regions := map[string]func() string{
		"uchu-ramps":       ramps,
		"sticker-swatches": stickerSwatches,
	}

	for _, p := range cssPaths {
		if err := fillRegions(p, regions); err != nil {
			die(err)
		}
	}
	if *goPath != "" {
		abs, err := filepath.Abs(*goPath)
		if err != nil {
			die(err)
		}
		write(*goPath, goSets(filepath.Base(filepath.Dir(abs))))
	}
	if *tsPath != "" {
		write(*tsPath, tsSets(split(*tsSetNames)))
	}
}

// fillRegions rewrites every GENERATED region the file actually declares, and
// leaves the rest alone — so core.css can carry the ramps and dope's layer the
// swatches without either knowing about the other.
func fillRegions(path string, regions map[string]func() string) error {
	src, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	body := string(src)
	for name, emit := range regions {
		begin := strings.Index(body, palette.BeginMarker(name))
		if begin < 0 {
			continue
		}
		head := begin + len(palette.BeginMarker(name))
		end := strings.Index(body[head:], palette.EndMarker)
		if end < 0 {
			return fmt.Errorf("%s: region %q is not closed", path, name)
		}
		body = body[:head] + "\n" + emit() + "  " + body[head+end:]
	}
	if string(src) == body {
		return nil
	}
	return os.WriteFile(path, []byte(body), 0o644)
}

// ramps emits every rung of both variants. All 164 ship, not just the ones a
// theme currently names: the whole point of a numbered ladder is that shifting a
// role one rung is an edit to one integer, and that only holds if the neighbour
// is already there. Gzip collapses the repetition to about a kilobyte.
func ramps() string {
	var b strings.Builder
	for _, name := range palette.Anchors() {
		fmt.Fprintf(&b, "  --uchu-%s: %s;\n", name, palette.Anchor(name).CSS())
	}
	for _, variant := range palette.Variants() {
		prefix := ""
		if variant == "pastel" {
			prefix = "pastel-"
		}
		for _, hue := range palette.Hues(variant) {
			b.WriteByte('\n')
			for n := 1; n <= 9; n++ {
				fmt.Fprintf(&b, "  --uchu-%s%s-%d: %s;\n", prefix, hue, n, palette.Rung(variant, hue, n).CSS())
			}
		}
	}
	return b.String()
}

func stickerSwatches() string {
	var b strings.Builder
	for _, c := range palette.Set("sticker") {
		fmt.Fprintf(&b, "  --sticker-c-%s: %s;\n", c.Name, c.Hex)
	}
	return b.String()
}

func goSets(pkg string) string {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/palettegen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n", pkg)
	for _, name := range palette.SetNames() {
		set := palette.Set(name)
		fmt.Fprintf(&b, "\n// %s is the %s colour set, in offer order.\nvar %s = []NamedColor{\n",
			exported(name), name, exported(name))
		for _, c := range set {
			fmt.Fprintf(&b, "\t{Name: %q, Hex: %q},\n", c.Name, c.Hex)
		}
		b.WriteString("}\n")
	}
	return b.String()
}

// split turns a comma list into names, or nil for "everything".
func split(s string) []string {
	if s == "" {
		return nil
	}
	return strings.Split(s, ",")
}

func tsSets(only []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/palettegen. DO NOT EDIT.\n")
	b.WriteString("// Source: dopeuikit/palette/sets.json + uchu.json.\n")
	for _, name := range palette.SetNames() {
		if only != nil && !slices.Contains(only, name) {
			continue
		}
		fmt.Fprintf(&b, "\n/** The %s colour set, in offer order. */\nexport const %s_COLORS: readonly string[] = [\n",
			name, strings.ToUpper(name))
		for _, c := range palette.Set(name) {
			fmt.Fprintf(&b, "  %q,\n", c.Hex)
		}
		b.WriteString("];\n")
	}
	// uchu's own ink and paper: the pickers weigh contrast against these two,
	// because that is the pair the palette was designed against.
	b.WriteString("\n/** uchu's ink — the dark end every rung was balanced against. */\n")
	fmt.Fprintf(&b, "export const YIN = %q;\n", palette.Anchor("yin").Hex())
	b.WriteString("\n/** uchu's paper. */\n")
	fmt.Fprintf(&b, "export const YANG = %q;\n", palette.Anchor("yang").Hex())
	return b.String()
}

func exported(s string) string {
	return strings.ToUpper(s[:1]) + s[1:] + "Colors"
}

func write(path, body string) {
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		die(err)
	}
}

func die(err error) {
	fmt.Fprintln(os.Stderr, "palettegen:", err)
	os.Exit(1)
}
