// Code generated by scripts/i18nstringsgen from i18nstrings/ru/*.toml. DO NOT EDIT.

import type { Strings } from "./i18nstrings_types_gen.js";

export const RU: Strings = {
  admin: {
    create: {
      empty: () => "Не указано ни одного логина.",
      skippedLead: () => "Уже существуют (пропущены): ",
      submit: () => "Создать",
      usernamesLabel: () => "Логины (по одному в строке)",
    },
    created: {
      copyLabel: () => "Для копирования (логин ⇥ пароль)",
      hint: () => "Пароли показаны один раз. Скопируйте и разошлите — пользователи сменят их сами.",
      password: () => "Пароль",
      username: () => "Логин",
    },
    errors: {
      title: () => "Ошибки:",
    },
  },
  chrome: {
    crumbs: {
      label: () => "Навигация",
    },
    sync: {
      error: () => "Ошибка",
      saved: () => "Готово",
      saving: () => "Подождите",
    },
  },
  login: {
    code: {
      botHintLead: () => "Если ссылка не открывается, напишите боту ",
      botHintMid: () => " и пришлите код ",
      linkHint: () => "Для входа пройдите по ссылке:",
      waiting: () => "Жду подтверждения от бота…",
    },
    field: {
      password: () => "Пароль",
      username: () => "Логин",
    },
    link: {
      cancel: () => "Это не я, выберу другой логин",
      hint: () => "Такой пользователь уже существует. Если это вы, введите пароль, чтобы привязать аккаунт.",
      submit: () => "Привязать",
    },
    message: {
      codeExpired: () => "Код истёк. Начните вход заново.",
      failed: () => "Что-то пошло не так, попробуйте снова.",
      tgMisconfigured: () => "Телеграм-логин настроен неверно.",
      tgUnreachable: () => "Бот для телеграм-логина недоступен.",
      timedOut: () => "Время ожидания вышло. Обновите страницу.",
      usernameTaken: () => "Логин занят, выберите другой.",
    },
    method: {
      hint: () => "Войдите, чтобы продолжить.",
      password: () => "Войти по паролю",
      telegram: () => "Войти через телеграм",
    },
    password: {
      hint: () => "Вход по паролю.",
      submit: () => "Войти",
    },
    title: () => "Вход",
    username: {
      hint: () => "Придумайте никнейм. Изменить его потом нельзя.",
      submit: () => "Продолжить",
    },
  },
  menu: {
    account: {
      login: () => "Вход",
      profile: () => "Профиль",
    },
    appearance: {
      contrast: () => "Контраст",
      contrastHigh: () => "Высокий",
      contrastRegular: () => "Обычный",
      done: () => "Готово",
      theme: () => "Тема",
      themeDark: () => "Тёмная",
      themeLight: () => "Светлая",
      themeSystem: () => "Системная",
      title: () => "Оформление",
    },
    jump: () => "Перейти",
    trigger: () => "Меню",
  },
};

export default RU;
