// Code generated by scripts/i18nstringsgen from i18nstrings/*/*.toml. DO NOT EDIT.

/** One language's Catalog: a key per Surface, a nested object per group,
 * a function per string. */
export type Strings = {
  admin: {
    create: {
      empty: () => string;
      skippedLead: () => string;
      submit: () => string;
      usernamesLabel: () => string;
    };
    created: {
      copyLabel: () => string;
      hint: () => string;
      password: () => string;
      username: () => string;
    };
    errors: {
      title: () => string;
    };
  };
  chrome: {
    crumbs: {
      label: () => string;
    };
    sync: {
      error: () => string;
      saved: () => string;
      saving: () => string;
    };
  };
  datetime: {
    calendar: {
      clear: () => string;
      done: () => string;
      dowFri: () => string;
      dowMon: () => string;
      dowSat: () => string;
      dowSun: () => string;
      dowThu: () => string;
      dowTue: () => string;
      dowWed: () => string;
      label: () => string;
      nextMonth: () => string;
      prevMonth: () => string;
      time: () => string;
      timezone: (zone: string) => string;
    };
  };
  login: {
    code: {
      botHintLead: () => string;
      botHintMid: () => string;
      linkHint: () => string;
      waiting: () => string;
    };
    field: {
      password: () => string;
      username: () => string;
    };
    link: {
      cancel: () => string;
      hint: () => string;
      submit: () => string;
    };
    message: {
      codeExpired: () => string;
      failed: () => string;
      tgMisconfigured: () => string;
      tgUnreachable: () => string;
      timedOut: () => string;
      usernameTaken: () => string;
    };
    method: {
      hint: () => string;
      password: () => string;
      telegram: () => string;
    };
    password: {
      hint: () => string;
      submit: () => string;
    };
    title: () => string;
    username: {
      hint: () => string;
      submit: () => string;
    };
  };
  menu: {
    account: {
      login: () => string;
      profile: () => string;
    };
    appearance: {
      contrast: () => string;
      contrastHigh: () => string;
      contrastRegular: () => string;
      done: () => string;
      theme: () => string;
      themeDark: () => string;
      themeLight: () => string;
      themeSystem: () => string;
      title: () => string;
    };
    jump: () => string;
    trigger: () => string;
  };
};
