// Code generated by scripts/i18nstringsgen from i18nstrings/en/*.toml. DO NOT EDIT.

import type { Strings } from "./i18nstrings_types_gen.js";

export const EN: Strings = {
  admin: {
    create: {
      empty: () => "No username was given.",
      skippedLead: () => "Already exist (skipped): ",
      submit: () => "Create",
      usernamesLabel: () => "Usernames (one per line)",
    },
    created: {
      copyLabel: () => "For copying (username ⇥ password)",
      hint: () => "The passwords are shown once. Copy them and send them out — people will change them themselves.",
      password: () => "Password",
      username: () => "Username",
    },
    errors: {
      title: () => "Errors:",
    },
  },
  chrome: {
    crumbs: {
      label: () => "Navigation",
    },
    sync: {
      error: () => "Error",
      saved: () => "Saved",
      saving: () => "Saving…",
    },
  },
  login: {
    code: {
      botHintLead: () => "If the link does not open, write to the bot ",
      botHintMid: () => " and send it the code ",
      linkHint: () => "Follow this link to log in:",
      waiting: () => "Waiting for the bot to confirm…",
    },
    field: {
      password: () => "Password",
      username: () => "Username",
    },
    link: {
      cancel: () => "That is not me, I will choose another username",
      hint: () => "That user already exists. If it is you, enter the password to link the account.",
      submit: () => "Link",
    },
    message: {
      codeExpired: () => "The code has expired. Start again.",
      copied: () => "copied",
      failed: () => "Something went wrong, try again.",
      tgMisconfigured: () => "Telegram login is set up wrongly.",
      tgUnreachable: () => "The Telegram login bot is unreachable.",
      timedOut: () => "The wait ran out. Reload the page.",
      usernameTaken: () => "That username is taken, choose another.",
    },
    method: {
      hint: () => "Log in to continue.",
      password: () => "Log in with a password",
      telegram: () => "Log in with Telegram",
    },
    password: {
      hint: () => "Logging in with a password.",
      submit: () => "Log in",
    },
    title: () => "Log in",
    username: {
      hint: () => "Choose a username. It cannot be changed later.",
      submit: () => "Continue",
    },
  },
  menu: {
    account: {
      login: () => "Log in",
      profile: () => "Profile",
    },
    appearance: {
      contrast: () => "Contrast",
      contrastHigh: () => "High",
      contrastRegular: () => "Regular",
      done: () => "Done",
      theme: () => "Theme",
      themeDark: () => "Dark",
      themeLight: () => "Light",
      themeSystem: () => "System",
      title: () => "Appearance",
    },
    jump: () => "Go to",
    trigger: () => "Menu",
  },
};

export default EN;
