// Code generated by scripts/i18nstringsgen from i18nstrings/*/*.toml. DO NOT EDIT.

/** One language's Catalog: a key per Surface, a nested object per group,
 * a function per string. */
export type Strings = {
  common: {
    cancel: () => string;
    save: () => string;
    selection: {
      count: (n: number) => string;
    };
  };
};
