// Code generated by scripts/i18nstringsgen. DO NOT EDIT.

export type Lang = "en";

/** The form of a counted noun. A language with no rule of its own gets the
 * English one/other shape out of one and many. */
export function plural(lang: Lang, n: number, one: string, few: string, many: string): string {
  const abs = Math.abs(n);
  return abs === 1 ? one : many;
}
