// Code generated by scripts/i18nstringsgen from i18nstrings/*/*.toml. DO NOT EDIT.

/** One language's Catalog: a key per Surface, a nested object per group,
 * a function per string. */
export type Strings = {
  admin: {
    createUsers: {
      name: () => string;
      title: () => string;
    };
    page: {
      title: () => string;
    };
  };
  auth: {
    login: {
      fieldsRequired: () => string;
      invalid: () => string;
    };
    page: {
      title: () => string;
    };
    tg: {
      codeMissing: () => string;
      notConfigured: () => string;
      telegramTaken: () => string;
    };
    username: {
      format: () => string;
      reserved: () => string;
    };
  };
  bot: {
    login: {
      hint: (url: string) => string;
    };
    register: {
      done: () => string;
      expired: () => string;
    };
    texts: {
      down: () => string;
      help: () => string;
    };
  };
  common: {
    cancel: () => string;
    save: () => string;
  };
  group: {
    error: {
      currencyUnknown: () => string;
      nameRequired: () => string;
      nameTooLong: () => string;
      notAMember: () => string;
      notSettled: (name: string, amount: string) => string;
      ownerMustHandOver: () => string;
      ownerOnly: () => string;
      stillNamed: (name: string) => string;
    };
  };
  invite: {
    error: {
      decisionInvalid: () => string;
      labelTooLong: () => string;
      limitsOutOfRange: () => string;
      noSeatsLeft: () => string;
      notFound: () => string;
      requestNotFound: () => string;
    };
    refusal: {
      declined: () => string;
      exhausted: () => string;
      expired: () => string;
      generic: () => string;
      revoked: () => string;
      spent: () => string;
    };
  };
  notify: {
    involved: {
      created: (group: string, description: string, link: string) => string;
      edited: (group: string, description: string, link: string) => string;
    };
    join: {
      text: (name: string, group: string, link: string) => string;
    };
    unclaimed: {
      text: (group: string, description: string, link: string) => string;
    };
  };
  page: {
    common: {
      home: () => string;
    };
    group: {
      add: () => string;
      balances: () => string;
      confirmDelete: () => string;
      confirmKick: (name: string) => string;
      confirmLeave: () => string;
      currencyLabel: () => string;
      debts: () => string;
      delete: () => string;
      deleted: () => string;
      handOver: () => string;
      handOverLabel: () => string;
      history: () => string;
      invites: () => string;
      kick: () => string;
      leave: () => string;
      members: () => string;
      nameLabel: () => string;
      newInvite: () => string;
      noRates: () => string;
      noTransactions: () => string;
      ownerTag: () => string;
      settings: () => string;
      settled: () => string;
      title: () => string;
      transactions: () => string;
      transfer: (from: string, to: string) => string;
      unclaimed: (amount: string) => string;
      you: () => string;
    };
    history: {
      created: () => string;
      deleted: () => string;
      edited: () => string;
      fieldDay: (before: string, after: string) => string;
      fieldDescription: (before: string, after: string) => string;
      fieldTotal: (before: string, after: string) => string;
      fieldUnclaimed: (before: string, after: string) => string;
      photoAdded: () => string;
      photoRemoved: () => string;
      restored: () => string;
      somebody: () => string;
    };
    index: {
      createSubmit: () => string;
      createTitle: () => string;
      currencyLabel: () => string;
      empty: () => string;
      heading: () => string;
      nameLabel: () => string;
      namePlaceholder: () => string;
      newGroup: () => string;
      settled: () => string;
      title: () => string;
    };
    invite: {
      approval: () => string;
      approve: () => string;
      copied: () => string;
      copy: () => string;
      decline: () => string;
      labelLabel: () => string;
      labelPlaceholder: () => string;
      maxUsesLabel: () => string;
      mint: () => string;
      remove: () => string;
      revoke: () => string;
      stateActive: () => string;
      stateExhausted: () => string;
      stateExpired: () => string;
      stateRevoked: () => string;
      ttlLabel: () => string;
      waiting: () => string;
    };
    join: {
      alreadyMember: () => string;
      anonymous: () => string;
      dead: () => string;
      invited: () => string;
      join: () => string;
      login: () => string;
      needsApproval: () => string;
      open: () => string;
      pending: () => string;
      title: () => string;
      unnamed: () => string;
    };
    transaction: {
      colFor: () => string;
      colPaid: () => string;
      colPercent: () => string;
      colShare: () => string;
      confirmDelete: () => string;
      confirmRemovePhoto: () => string;
      currency: () => string;
      day: () => string;
      delete: () => string;
      description: () => string;
      descriptionPlaceholder: () => string;
      fullyClaimed: () => string;
      hintClaim: () => string;
      hintEven: () => string;
      hintExact: () => string;
      hintPercent: () => string;
      hintSettlement: () => string;
      hintSimple: () => string;
      history: () => string;
      mode: () => string;
      modeClaim: () => string;
      modeEven: () => string;
      modeExact: () => string;
      modePercent: () => string;
      modeSettlement: () => string;
      modeSimple: () => string;
      needMembers: () => string;
      needPayee: () => string;
      needPayer: () => string;
      needPaymentsMatch: () => string;
      needPercents: () => string;
      needSharesFit: () => string;
      newTitle: () => string;
      noPhotos: () => string;
      photoAlt: () => string;
      photos: () => string;
      pickPhoto: () => string;
      rateAsOf: (day: string) => string;
      removePhoto: () => string;
      restore: () => string;
      title: () => string;
      total: () => string;
      unclaimedNote: (amount: string) => string;
      upload: () => string;
    };
  };
  profile: {
    logout: () => string;
    password: {
      current: () => string;
      currentWrong: () => string;
      hint: () => string;
      length: () => string;
      mismatch: () => string;
      new: () => string;
      repeat: () => string;
      saved: () => string;
      submit: () => string;
      title: () => string;
    };
    telegram: {
      accountTaken: () => string;
      botLead: () => string;
      botMid: () => string;
      expired: () => string;
      hint: () => string;
      linkHint: () => string;
      linked: () => string;
      linkedLead: () => string;
      linkedTail: () => string;
      none: () => string;
      start: () => string;
      timedOut: () => string;
      title: () => string;
      waiting: () => string;
    };
    title: () => string;
    whoami: {
      lead: () => string;
      tail: () => string;
    };
  };
  server: {
    error: {
      badRequest: () => string;
      internal: () => string;
      notFound: () => string;
    };
  };
  transaction: {
    error: {
      currencyInvalid: () => string;
      dayInvalid: () => string;
      deleted: () => string;
      descriptionRequired: () => string;
      descriptionTooLong: () => string;
      duplicateMember: () => string;
      negativeAmount: () => string;
      notAMember: () => string;
      paymentRequired: () => string;
      paymentsMismatch: (paid: string, total: string) => string;
      photoMissing: () => string;
      photoNotAnImage: () => string;
      photoTooLarge: () => string;
      sharesOverdraw: (over: string) => string;
      totalPositive: () => string;
    };
  };
};
