// Command uigen generates internal/ui/tags_gen.go from vocab.json: element
// constructors, attribute constructors and ClassToken constants. Run via
// `go generate ./internal/ui` (wired as a //go:generate directive in
// vocab.go).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"

	"xy/internal/ui"
)

// elementCtorOverrides / classOverrides rename generated identifiers that
// would otherwise collide with another generated identifier in the same
// package (Go has no element-vs-class-vs-attr namespaces).
var (
	// attrCtorSkip are hand-written in builder.go with bespoke signatures
	// (Class takes ...ClassToken, not a plain string) instead of generated.
	attrCtorSkip = map[string]bool{"id": true, "class": true}

	// attrCtorOverrides: "title" the attribute would generate "Title", which
	// collides with the Title() ctor for the <title> element.
	attrCtorOverrides = map[string]string{"title": "TitleAttr"}

	// classOverrides: these class tokens pascal-case to the same identifier
	// as an element constructor (Input, Section).
	classOverrides = map[string]string{"input": "InputClass", "section": "SectionClass"}
)

func pascal(s string) string {
	parts := strings.Split(s, "-")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String()
}

func main() {
	in := flag.String("in", "vocab.json", "vocab.json path")
	out := flag.String("out", "tags_gen.go", "output .go path")
	flag.Parse()

	data, err := os.ReadFile(*in)
	if err != nil {
		fmt.Fprintln(os.Stderr, "uigen:", err)
		os.Exit(1)
	}
	vocab, err := ui.LoadVocab(data)
	if err != nil {
		fmt.Fprintln(os.Stderr, "uigen:", err)
		os.Exit(1)
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/uigen from vocab.json. DO NOT EDIT.\n\n")
	b.WriteString("package ui\n\n")

	b.WriteString("// Element constructors.\n\n")
	for _, e := range vocab.Elements {
		name := pascal(e.Tag)
		fmt.Fprintf(&b, "func %s(items ...Item) *Element {\n\treturn newElement(%q, items)\n}\n\n", name, e.Tag)
	}

	b.WriteString("// Attribute constructors.\n\n")
	for _, a := range vocab.Attrs {
		if attrCtorSkip[a.Name] {
			continue
		}
		name := pascal(a.Name)
		if override, ok := attrCtorOverrides[a.Name]; ok {
			name = override
		}
		switch a.Kind {
		case "bare":
			fmt.Fprintf(&b, "func %s() Attr {\n\treturn Attr{Name: %q, Bare: true}\n}\n\n", name, a.Name)
		default:
			fmt.Fprintf(&b, "func %s(v string) Attr {\n\treturn Attr{Name: %q, Value: v}\n}\n\n", name, a.Name)
		}
	}

	b.WriteString("// ClassToken constants: the closed class-token whitelist (type declared in builder.go).\n\n")
	for _, c := range vocab.Classes {
		name := pascal(c)
		if override, ok := classOverrides[c]; ok {
			name = override
		}
		fmt.Fprintf(&b, "const %s ClassToken = %q\n", name, c)
	}
	b.WriteString("\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, "uigen: gofmt generated source:", err)
		os.Stderr.Write(b.Bytes())
		os.Exit(1)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "uigen:", err)
		os.Exit(1)
	}
}
