// Command uigen generates internal/ui/tags_gen.go from vocab.json: one typed
// constructor per primitive, one prop constructor per string/bare prop, and one
// Attr constant per enum value. Run via `go generate ./internal/ui` (wired as a
// //go:generate directive in vocab.go).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"xy/internal/ui"
)

// Identifier overrides resolve clashes between generated names (Go has no
// primitive-vs-prop-vs-leaf namespaces).
var (
	// primCtorOverrides: primitive ctors that would collide with a leaf helper
	// (Text) or a prop ctor (Label).
	primCtorOverrides = map[string]string{"text": "Paragraph", "label": "SectionLabel"}

	// propCtorOverrides: prop ctors that would collide with a primitive ctor.
	propCtorOverrides = map[string]string{"hint": "SliderHint"}

	// propCtorSkip: hand-written in builder.go (ID) with a bespoke role.
	propCtorSkip = map[string]bool{"id": true}
)

func pascal(s string) string {
	var b strings.Builder
	for _, p := range strings.Split(s, "-") {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String()
}

// enumConst names an enum value: short tokens (xs, sm) upper-cased whole,
// longer ones Pascal-cased (board-grid -> BoardGrid).
func enumConst(prefix, value string) string {
	tok := pascal(value)
	if len(value) <= 2 {
		tok = strings.ToUpper(value)
	}
	return prefix + tok
}

func main() {
	in := flag.String("in", "vocab.json", "vocab.json path")
	out := flag.String("out", "tags_gen.go", "output .go path")
	flag.Parse()

	data, err := os.ReadFile(*in)
	if err != nil {
		die(err)
	}
	vocab, err := ui.LoadVocab(data)
	if err != nil {
		die(err)
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/uigen from vocab.json. DO NOT EDIT.\n\n")
	b.WriteString("package ui\n\n")

	writePrimitives(&b, vocab)
	writeProps(&b, vocab)
	writeEnums(&b, vocab)

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, "uigen: gofmt generated source:", err)
		os.Stderr.Write(b.Bytes())
		os.Exit(1)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		die(err)
	}
}

func writePrimitives(b *bytes.Buffer, v *ui.Vocab) {
	b.WriteString("// Primitive constructors.\n\n")
	for _, p := range v.Primitives {
		name := pascal(p.Name)
		if o, ok := primCtorOverrides[p.Name]; ok {
			name = o
		}
		fmt.Fprintf(b, "func %s(items ...Item) *Element {\n\treturn newElement(%q, items)\n}\n\n", name, p.Name)
	}
}

// writeProps emits one ctor per distinct string/bare prop (enum props get value
// consts instead), across every primitive plus the universal props.
func writeProps(b *bytes.Buffer, v *ui.Vocab) {
	type propInfo struct {
		name string
		bare bool
	}
	seen := map[string]bool{}
	var props []propInfo
	add := func(ps ui.PropSpec) {
		if ps.Enum != "" || propCtorSkip[ps.Name] || seen[ps.Name] {
			return
		}
		seen[ps.Name] = true
		props = append(props, propInfo{name: ps.Name, bare: ps.Kind == "bare"})
	}
	for _, u := range v.Universal {
		add(u)
	}
	for _, p := range v.Primitives {
		for _, ps := range p.Props {
			add(ps)
		}
	}

	b.WriteString("// Prop constructors.\n\n")
	for _, p := range props {
		name := pascal(p.name)
		if o, ok := propCtorOverrides[p.name]; ok {
			name = o
		}
		if p.bare {
			fmt.Fprintf(b, "func %s() Attr {\n\treturn Attr{Name: %q, Bare: true}\n}\n\n", name, p.name)
		} else {
			fmt.Fprintf(b, "func %s(v string) Attr {\n\treturn Attr{Name: %q, Value: v}\n}\n\n", name, p.name)
		}
	}
}

// writeEnums emits every enum value as an Attr constant carrying its prop name,
// so builder callers write ui.SpaceSM / ui.Ghost / ui.PageFull directly.
func writeEnums(b *bytes.Buffer, v *ui.Vocab) {
	propOf := enumProps(v)
	b.WriteString("// Enum value constants (each carries its prop name).\n\n")
	names := make([]string, 0, len(v.Enums))
	for n := range v.Enums {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		e := v.Enums[n]
		prop := propOf[n]
		for _, val := range e.Values {
			fmt.Fprintf(b, "var %s = Attr{Name: %q, Value: %q}\n", enumConst(e.Prefix, val), prop, val)
		}
		b.WriteString("\n")
	}
}

func enumProps(v *ui.Vocab) map[string]string {
	out := map[string]string{}
	for _, p := range v.Primitives {
		for _, ps := range p.Props {
			if ps.Enum != "" {
				out[ps.Enum] = ps.Name
			}
		}
	}
	return out
}

func die(err error) {
	fmt.Fprintln(os.Stderr, "uigen:", err)
	os.Exit(1)
}
