// genmarkers writes web/ts/markers_gen.ts from fsource's marker table, so the
// TypeScript 4s reader and the Go one cannot drift on what a marker is.
package main

import (
	"fmt"
	"log"
	"os"
	"sort"
	"strings"
	"unicode/utf8"

	"xy/internal/chgk/fsource"
)

func main() {
	types := fsource.MarkerTypes()
	markers := make([]string, 0, len(types))
	for m := range types {
		markers = append(markers, m)
	}
	// Longest first, so a reader that tries them in order matches "###" before
	// "#"; ties in byte order, for a stable file.
	sort.Slice(markers, func(i, j int) bool {
		li, lj := utf8.RuneCountInString(markers[i]), utf8.RuneCountInString(markers[j])
		if li != lj {
			return li > lj
		}
		return markers[i] < markers[j]
	})
	var b strings.Builder
	b.WriteString("// Code generated by internal/chgk/fsource/genmarkers from fsource.markerMapping. DO NOT EDIT.\n\n")
	b.WriteString("// The 4s line markers and the element type each opens, longest first — the\n")
	b.WriteString("// same table fsource.Parse reads by, so the browser's reader and the server's\n")
	b.WriteString("// agree on what a marked line is.\n")
	b.WriteString("export const MARKERS = [\n")
	for _, m := range markers {
		fmt.Fprintf(&b, "  [%q, %q],\n", m, types[m])
	}
	b.WriteString("] as const;\n\n")
	b.WriteString("export type MarkerType = (typeof MARKERS)[number][1];\n")
	out := "web/ts/markers_gen.ts"
	if len(os.Args) > 1 {
		out = os.Args[1]
	}
	// go generate runs in the package directory; the file lives at the repo root.
	if _, err := os.Stat(out); err != nil {
		out = "../../../" + out
	}
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		log.Fatal(err)
	}
}
