// Code generated by cmd/palettegen. DO NOT EDIT.

package palette

// StickerColors is the sticker colour set, in offer order.
var StickerColors = []NamedColor{
	{Name: "white", Hex: "#ffffff"},
	{Name: "yellow", Hex: "#fdf66f"},
	{Name: "green", Hex: "#aded87"},
	{Name: "red", Hex: "#ff7a6b"},
	{Name: "blue", Hex: "#68caff"},
	{Name: "pink", Hex: "#f4a8ff"},
	{Name: "orange", Hex: "#ffae37"},
}
