// Package uigen generates the typed Go builder (tags_gen.go) from a vocabulary.
// Every generated package layers over a base import: it re-exports the base's
// node types, builder leaves, and (in overlay mode) its constructors/consts,
// then adds constructors and enum constants for the vocabulary's own additions,
// so app code imports exactly one package. Core mode is the empty-base case: the
// kit's builder over the ui engine, with a constructor for every primitive.
package uigen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"pecheny.me/dopeuikit/ui"
)

// Identifier overrides resolve clashes between generated names (Go has no
// primitive-vs-prop-vs-leaf namespaces).
var (
	primCtorOverrides = map[string]string{"text": "Paragraph", "label": "SectionLabel"}
	propCtorOverrides = map[string]string{"hint": "SliderHint", "list": "InputList"}
	propCtorSkip      = map[string]bool{"id": true}
)

func pascal(s string) string {
	var b strings.Builder
	for _, p := range strings.Split(s, "-") {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String()
}

// enumConst names an enum value: short tokens (xs, sm) upper-cased whole,
// longer ones Pascal-cased (board-grid -> BoardGrid).
func enumConst(prefix, value string) string {
	tok := pascal(value)
	if len(value) <= 2 {
		tok = strings.ToUpper(value)
	}
	return prefix + tok
}

func primName(name string) string {
	if o, ok := primCtorOverrides[name]; ok {
		return o
	}
	return pascal(name)
}

func propName(name string) string {
	if o, ok := propCtorOverrides[name]; ok {
		return o
	}
	return pascal(name)
}

// Core generates a self-contained builder for a vocabulary as its own package
// over the ui engine (the kit's tags_gen.go, package kit, base pecheny.me/
// dopeuikit/ui): type/leaf re-exports plus a constructor for every primitive and
// prop and an Attr constant per enum value. It is the empty-base case of Overlay.
func Core(v *ui.Vocab, pkg, basePkg string) ([]byte, error) {
	return Overlay(&ui.Vocab{}, v, pkg, basePkg)
}

// Overlay generates a builder package layered over basePkg: re-export shims for
// every base constructor/const, plus constructors and enum consts for the
// vocabulary's own additions (everything in merged that is not already in base).
// pkg is the emitted package name; basePkg is the import path of the base layer.
func Overlay(base, merged *ui.Vocab, pkg, basePkg string) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/uigen from vocab.json. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "import base %q\n\n", basePkg)

	b.WriteString("// Node types, re-exported so app code imports one package.\n")
	for _, t := range []string{"Doc", "Node", "Item", "Attr", "Element", "TextNode", "RunNode", "Comment", "BlankLine", "Doctype"} {
		fmt.Fprintf(&b, "type %s = base.%s\n", t, t)
	}
	b.WriteString("\n// Builder leaves, re-exported.\n")
	for _, f := range []string{"New", "Text", "Line", "Inline", "CommentNode", "Blank", "ID", "Aria", "Data"} {
		fmt.Fprintf(&b, "var %s = base.%s\n", f, f)
	}

	if len(base.Primitives) > 0 {
		b.WriteString("\n// Base primitive constructors, re-exported.\n")
		for _, p := range base.Primitives {
			fmt.Fprintf(&b, "var %s = base.%s\n", primName(p.Name), primName(p.Name))
		}
	}
	if baseProps := collectProps(base); len(baseProps) > 0 {
		b.WriteString("\n// Base prop constructors, re-exported.\n")
		for _, pi := range baseProps {
			fmt.Fprintf(&b, "var %s = base.%s\n", propName(pi.name), propName(pi.name))
		}
	}
	if baseEnums := enumConstNames(base); len(baseEnums) > 0 {
		b.WriteString("\n// Base enum constants, re-exported.\n")
		for _, name := range baseEnums {
			fmt.Fprintf(&b, "var %s = base.%s\n", name, name)
		}
	}

	if prims := diffPrimitives(base, merged); len(prims) > 0 {
		b.WriteString("\n// Primitive constructors.\n\n")
		for _, p := range prims {
			fmt.Fprintf(&b, "func %s(items ...Item) *Element {\n\treturn base.New(%q, items...)\n}\n\n", primName(p.Name), p.Name)
		}
	}
	if newProps := diffProps(base, merged); len(newProps) > 0 {
		b.WriteString("// Prop constructors.\n\n")
		for _, pi := range newProps {
			if pi.bare {
				fmt.Fprintf(&b, "func %s() Attr {\n\treturn Attr{Name: %q, Bare: true}\n}\n\n", propName(pi.name), pi.name)
			} else {
				fmt.Fprintf(&b, "func %s(v string) Attr {\n\treturn Attr{Name: %q, Value: v}\n}\n\n", propName(pi.name), pi.name)
			}
		}
	}

	if newEnums := diffEnumConsts(base, merged); len(newEnums) > 0 {
		b.WriteString("// Enum value constants (each carries its prop name).\n\n")
		for _, e := range newEnums {
			fmt.Fprintf(&b, "var %s = Attr{Name: %q, Value: %q}\n", e.constName, e.prop, e.value)
		}
	}
	return format.Source(b.Bytes())
}

type enumConstInfo struct {
	constName, prop, value string
}

// enumConstNames returns the const names for every enum value in v, in the
// deterministic (sorted-enum) order the generator emits them.
func enumConstNames(v *ui.Vocab) []string {
	var out []string
	for _, n := range sortedEnums(v) {
		e := v.Enums[n]
		for _, val := range e.Values {
			out = append(out, enumConst(e.Prefix, val))
		}
	}
	return out
}

// diffEnumConsts returns enum value constants present in merged but not in base
// (new enums and values added to base enums).
func diffEnumConsts(base, merged *ui.Vocab) []enumConstInfo {
	propOf := enumProps(merged)
	var out []enumConstInfo
	for _, n := range sortedEnums(merged) {
		me := merged.Enums[n]
		baseVals := map[string]bool{}
		if be, ok := base.Enums[n]; ok {
			for _, v := range be.Values {
				baseVals[v] = true
			}
		}
		for _, val := range me.Values {
			if baseVals[val] {
				continue
			}
			out = append(out, enumConstInfo{constName: enumConst(me.Prefix, val), prop: propOf[n], value: val})
		}
	}
	return out
}

type propInfo struct {
	name string
	bare bool
}

func collectProps(v *ui.Vocab) []propInfo {
	seen := map[string]bool{}
	var props []propInfo
	add := func(ps ui.PropSpec) {
		if ps.Enum != "" || propCtorSkip[ps.Name] || seen[ps.Name] {
			return
		}
		seen[ps.Name] = true
		props = append(props, propInfo{name: ps.Name, bare: ps.Kind == "bare"})
	}
	for _, u := range v.Universal {
		add(u)
	}
	for _, p := range v.Primitives {
		for _, ps := range p.Props {
			add(ps)
		}
	}
	return props
}

// diffProps returns props present in merged but not in core (by name).
func diffProps(core, merged *ui.Vocab) []propInfo {
	have := map[string]bool{}
	for _, pi := range collectProps(core) {
		have[pi.name] = true
	}
	var out []propInfo
	for _, pi := range collectProps(merged) {
		if !have[pi.name] {
			out = append(out, pi)
		}
	}
	return out
}

func diffPrimitives(core, merged *ui.Vocab) []ui.PrimitiveSpec {
	have := map[string]bool{}
	for _, p := range core.Primitives {
		have[p.Name] = true
	}
	var out []ui.PrimitiveSpec
	for _, p := range merged.Primitives {
		if !have[p.Name] {
			out = append(out, p)
		}
	}
	return out
}

func enumProps(v *ui.Vocab) map[string]string {
	out := map[string]string{}
	for _, p := range v.Primitives {
		for _, ps := range p.Props {
			if ps.Enum != "" {
				out[ps.Enum] = ps.Name
			}
		}
	}
	return out
}

func sortedEnums(v *ui.Vocab) []string {
	names := make([]string, 0, len(v.Enums))
	for n := range v.Enums {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}
