import { test } from "node:test";
import assert from "node:assert/strict";
import { xyDragRank } from "../web/assets/static/dist/dragrank.js";
import { xyRank } from "../web/assets/static/dist/rank.js";

const { byRank, dragAfterIndex, dragAfterIndexX, dragAfterIn, dragAfterInX, rankAfterMove, rankForSlot } = xyDragRank;
const { keyBetween } = xyRank;

// ---- byRank ----

test("byRank sorts by rank string, equal ranks compare 0", () => {
  const sorted = [{ rank: "a2" }, { rank: "a0V" }, { rank: "a1" }].sort(byRank);
  assert.deepEqual(sorted.map((c) => c.rank), ["a0V", "a1", "a2"]);
  assert.equal(byRank({ rank: "a1" }, { rank: "a1" }), 0);
});

// ---- geometry: dragAfterIndex over rects ----
// Rects at tops 0/100/200, height 80 → midlines at 40/140/240. The decision is:
// insert before the nearest rect whose midline is still below the pointer.

const vrects = [
  { top: 0, height: 80 },
  { top: 100, height: 80 },
  { top: 200, height: 80 },
];

test("dragAfterIndex: empty list appends", () => {
  assert.equal(dragAfterIndex([], 50), null);
});

test("dragAfterIndex: pointer above the first midline → index 0", () => {
  assert.equal(dragAfterIndex(vrects, 0), 0);
  assert.equal(dragAfterIndex(vrects, 39), 0);
});

test("dragAfterIndex: pointer between midlines → the following rect", () => {
  assert.equal(dragAfterIndex(vrects, 100), 1); // 40 < 100 < 140
  assert.equal(dragAfterIndex(vrects, 150), 2); // 140 < 150 < 240
});

test("dragAfterIndex: pointer exactly on a midline belongs after it", () => {
  assert.equal(dragAfterIndex(vrects, 140), 2);
});

test("dragAfterIndex: pointer below every midline appends", () => {
  assert.equal(dragAfterIndex(vrects, 300), null);
});

test("dragAfterIndexX mirrors the decision horizontally", () => {
  const hrects = [
    { left: 0, width: 40 },
    { left: 50, width: 40 },
    { left: 100, width: 40 },
  ]; // midlines 20/70/120
  assert.equal(dragAfterIndexX([], 10), null);
  assert.equal(dragAfterIndexX(hrects, 10), 0);
  assert.equal(dragAfterIndexX(hrects, 60), 1);
  assert.equal(dragAfterIndexX(hrects, 200), null);
});

// ---- geometry: Element adapters ----

test("dragAfterIn returns the element, not the index", () => {
  const els = vrects.map((r) => ({ getBoundingClientRect: () => r }));
  assert.equal(dragAfterIn(els, 100), els[1]);
  assert.equal(dragAfterIn(els, 300), null);
});

test("dragAfterInX returns the element, not the index", () => {
  const els = [
    { getBoundingClientRect: () => ({ left: 0, width: 40 }) },
    { getBoundingClientRect: () => ({ left: 50, width: 40 }) },
  ];
  assert.equal(dragAfterInX(els, 60), els[1]);
  assert.equal(dragAfterInX(els, 200), null);
});

// ---- rankAfterMove ----
// Fixture: four ranks generated by successive appends, so r[0] < r[1] < r[2] < r[3].

function fixture() {
  const r = [];
  let k = null;
  for (let i = 0; i < 4; i++) { k = keyBetween(k, null); r.push(k); }
  const ranks = new Map([[1, r[0]], [2, r[1]], [3, r[2]], [4, r[3]]]);
  return { r, rankOf: (id) => ranks.get(id) ?? null };
}

test("rankAfterMove: drop at head sorts before the old first card", () => {
  const { r, rankOf } = fixture();
  const rank = rankAfterMove([9, 1, 2, 3], 9, rankOf);
  assert.ok(rank < r[0], `${rank} < ${r[0]}`);
});

test("rankAfterMove: drop at tail sorts after the old last card", () => {
  const { r, rankOf } = fixture();
  const rank = rankAfterMove([1, 2, 3, 9], 9, rankOf);
  assert.ok(rank > r[2], `${rank} > ${r[2]}`);
});

test("rankAfterMove: drop between two cards sorts strictly between them", () => {
  const { r, rankOf } = fixture();
  const rank = rankAfterMove([1, 9, 2], 9, rankOf);
  assert.ok(r[0] < rank && rank < r[1], `${r[0]} < ${rank} < ${r[1]}`);
});

test("rankAfterMove: same-list move — only the new DOM neighbours matter", () => {
  const { r, rankOf } = fixture();
  // Card 4 (last by rank) dragged between 1 and 2; its own old rank r[3]
  // must not clamp the result upward.
  const rank = rankAfterMove([1, 4, 2, 3], 4, rankOf);
  assert.ok(r[0] < rank && rank < r[1], `${r[0]} < ${rank} < ${r[1]}`);
});

test("rankAfterMove: drop into an empty list yields the first key", () => {
  const { rankOf } = fixture();
  assert.equal(rankAfterMove([9], 9, rankOf), keyBetween(null, null));
});

test("rankAfterMove: out-of-order neighbour ranks drop the next bound", () => {
  const { r, rankOf } = fixture();
  // DOM says 2 then 1, but rank(2) > rank(1): the guard must discard next
  // instead of throwing, landing after prev.
  const rank = rankAfterMove([2, 9, 1], 9, rankOf);
  assert.ok(rank > r[1], `${rank} > ${r[1]}`);
});

// ---- rankForSlot ----

function slotFixture() {
  const { r } = fixture();
  // deliberately unsorted input — rankForSlot must sort by rank itself
  return { r, cards: [{ id: 2, rank: r[1] }, { id: 3, rank: r[2] }, { id: 1, rank: r[0] }] };
}

test("rankForSlot: empty list, end and slot 1 both yield the first key", () => {
  assert.equal(rankForSlot([], "end"), keyBetween(null, null));
  assert.equal(rankForSlot([], "1"), keyBetween(null, null));
});

test("rankForSlot: slot 1 sorts before every card", () => {
  const { r, cards } = slotFixture();
  const rank = rankForSlot(cards, "1");
  assert.ok(rank < r[0], `${rank} < ${r[0]}`);
});

test("rankForSlot: middle slot sorts strictly between its neighbours", () => {
  const { r, cards } = slotFixture();
  const rank = rankForSlot(cards, "2");
  assert.ok(r[0] < rank && rank < r[1], `${r[0]} < ${rank} < ${r[1]}`);
});

test("rankForSlot: end sorts after the last card", () => {
  const { r, cards } = slotFixture();
  const rank = rankForSlot(cards, "end");
  assert.ok(rank > r[2], `${rank} > ${r[2]}`);
});

test("rankForSlot: slot past the end degrades to the open-ends key (preserved quirk)", () => {
  const { cards } = slotFixture();
  assert.equal(rankForSlot(cards, "5"), keyBetween(null, null));
});

test("rankForSlot: excludeId drops the moving card from the neighbour set", () => {
  const { r, cards } = slotFixture();
  // moving card 2 to slot 3 of [1, 3] → after card 3
  const rank = rankForSlot(cards, "3", 2);
  assert.ok(rank > r[2], `${rank} > ${r[2]}`);
  // moving card 1 to slot 1 of [2, 3] → before card 2
  const head = rankForSlot(cards, "1", 1);
  assert.ok(head < r[1], `${head} < ${r[1]}`);
});

test("rankForSlot: duplicate neighbour ranks fall back to append-after-prev", () => {
  const cards = [{ id: 1, rank: "a1" }, { id: 2, rank: "a1" }];
  const rank = rankForSlot(cards, "2");
  assert.ok(rank > "a1", `${rank} > a1`);
});
