package main

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
)

const goHeader = "// Code generated by scripts/i18nstringsgen from i18nstrings/%s/*.toml. DO NOT EDIT.\n\npackage i18nstrings\n\n"

func emitGoTypes(ref *catalog) ([]byte, error) {
	var b strings.Builder
	fmt.Fprintf(&b, goHeader, "*")
	b.WriteString("// Strings is one language's Catalog: a field per Surface, a nested struct\n" +
		"// per group, a func per string.\ntype Strings struct {\n")
	for _, s := range ref.surfaces {
		fmt.Fprintf(&b, "\t%s %sStrings\n", pascal(s.name), pascal(s.name))
	}
	b.WriteString("}\n")
	for _, s := range ref.surfaces {
		fmt.Fprintf(&b, "\n// %sStrings is the %s Surface.\ntype %sStrings struct {\n", pascal(s.name), s.name, pascal(s.name))
		for _, f := range surfaceFields(s) {
			if f.group != nil {
				fmt.Fprintf(&b, "\t%s %s%sStrings\n", pascal(f.name), pascal(s.name), pascal(f.name))
				continue
			}
			fmt.Fprintf(&b, "\t%s func%s string\n", pascal(f.name), goSignature(f.str))
		}
		b.WriteString("}\n")
		for _, g := range s.groups {
			fmt.Fprintf(&b, "\ntype %s%sStrings struct {\n", pascal(s.name), pascal(g.name))
			for _, e := range g.strings {
				fmt.Fprintf(&b, "\t%s func%s string\n", pascal(e.key), goSignature(e))
			}
			b.WriteString("}\n")
		}
	}
	emitGoLookup(&b, ref)
	return format.Source([]byte(b.String()))
}

// emitGoLookup is the .dopeui side: `label=@common.save` resolves through these
// two, so the expander needs no reflection and the id set is closed here.
func emitGoLookup(b *strings.Builder, ref *catalog) {
	byID := ref.byID()
	var plain, all []string
	for _, id := range ref.ids() {
		all = append(all, id)
		if len(byID[id].params) == 0 {
			plain = append(plain, id)
		}
	}
	b.WriteString("\n// Lookup returns an untemplated string by its String Id, for `@surface.key`\n// in a .dopeui page.\nfunc (s Strings) Lookup(id string) (string, bool) {\n")
	if len(plain) > 0 {
		b.WriteString("\tswitch id {\n")
		for _, id := range plain {
			fmt.Fprintf(b, "\tcase %q:\n\t\treturn s.%s(), true\n", id, goPath(id))
		}
		b.WriteString("\t}\n")
	}
	b.WriteString("\treturn \"\", false\n}\n")
	b.WriteString("\n// Defines reports whether the Catalog holds the id at all, templated or not.\nfunc (Strings) Defines(id string) bool {\n")
	if len(all) > 0 {
		b.WriteString("\tswitch id {\n\tcase ")
		quoted := make([]string, len(all))
		for i, id := range all {
			quoted[i] = fmt.Sprintf("%q", id)
		}
		b.WriteString(strings.Join(quoted, ", ") + ":\n\t\treturn true\n\t}\n")
	}
	b.WriteString("\treturn false\n}\n")
}

// goPath turns surface.group.key into the Strings field path Board.Delete.Confirm.
func goPath(id string) string {
	parts := strings.Split(id, ".")
	for i, p := range parts {
		parts[i] = pascal(p)
	}
	return strings.Join(parts, ".")
}

func emitGoCatalog(c *catalog) ([]byte, error) {
	var body strings.Builder
	fmt.Fprintf(&body, "// %s is the %s Catalog.\nvar %s = Strings{\n", varName(c.lang), c.lang, varName(c.lang))
	for _, s := range c.surfaces {
		fmt.Fprintf(&body, "%s: %sStrings{\n", pascal(s.name), pascal(s.name))
		for _, f := range surfaceFields(s) {
			if f.group == nil {
				fmt.Fprintf(&body, "%s: %s,\n", pascal(f.name), goFunc(c.lang, f.str))
				continue
			}
			fmt.Fprintf(&body, "%s: %s%sStrings{\n", pascal(f.name), pascal(s.name), pascal(f.name))
			for _, e := range f.group.strings {
				fmt.Fprintf(&body, "%s: %s,\n", pascal(e.key), goFunc(c.lang, e))
			}
			body.WriteString("},\n")
		}
		body.WriteString("},\n")
	}
	body.WriteString("}\n")

	var b strings.Builder
	fmt.Fprintf(&b, goHeader, c.lang)
	text := body.String()
	var imports []string
	if strings.Contains(text, "fmt.Sprintf") {
		imports = append(imports, `"fmt"`)
	}
	if strings.Contains(text, "core.Plural") {
		imports = append(imports, `core "pecheny.me/dopecore/i18nstrings"`)
	}
	if len(imports) > 0 {
		fmt.Fprintf(&b, "import (\n%s\n)\n\n", strings.Join(imports, "\n\n"))
	}
	b.WriteString(text)
	return format.Source([]byte(b.String()))
}

func goFunc(lang string, e *str) string {
	var f strings.Builder
	var args []string
	for _, c := range e.chunks {
		switch c.kind {
		case chunkText:
			f.WriteString(strings.ReplaceAll(c.text, "%", "%%"))
		case chunkField:
			if isInt(e, c.param) {
				f.WriteString("%d")
			} else {
				f.WriteString("%s")
			}
			args = append(args, c.param)
		case chunkPlural:
			f.WriteString("%s")
			args = append(args, fmt.Sprintf("core.Plural(%q, %s, %q, %q, %q)",
				lang, c.param, c.forms[0], c.forms[1], c.forms[2]))
		}
	}
	if len(args) == 0 {
		return fmt.Sprintf("func() string { return %q }", literal(e))
	}
	return fmt.Sprintf("func%s string { return fmt.Sprintf(%q, %s) }",
		goSignature(e), f.String(), strings.Join(args, ", "))
}

func goSignature(e *str) string {
	var parts []string
	for _, p := range e.params {
		kind := "string"
		if p.isInt {
			kind = "int"
		}
		parts = append(parts, p.name+" "+kind)
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func isInt(e *str, name string) bool {
	for _, p := range e.params {
		if p.name == name {
			return p.isInt
		}
	}
	return false
}

// field is either a bare key or a group, so a Surface's members sort as one.
type field struct {
	name  string
	str   *str
	group *group
}

func surfaceFields(s *surface) []field {
	var out []field
	for _, e := range s.bare {
		out = append(out, field{name: e.key, str: e})
	}
	for _, g := range s.groups {
		out = append(out, field{name: g.name, group: g})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out
}

func pascal(name string) string {
	var b strings.Builder
	for _, part := range strings.Split(name, "_") {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return b.String()
}

func camel(name string) string {
	p := pascal(name)
	if p == "" {
		return p
	}
	return strings.ToLower(p[:1]) + p[1:]
}

func varName(lang string) string { return strings.ToUpper(lang) }
