package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

const tsHeader = "// Code generated by scripts/i18nstringsgen from i18nstrings/%s/*.toml. DO NOT EDIT.\n\n"

// emitTSPlural is the browser half of dopecore/i18nstrings.Plural. It is
// generated rather than hand-written so every TS tree gets the same copy the
// way icons_gen.ts does.
func emitTSPlural(langs []string) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by scripts/i18nstringsgen. DO NOT EDIT.\n\n")
	quoted := make([]string, len(langs))
	for i, l := range langs {
		quoted[i] = jsonString(l)
	}
	fmt.Fprintf(&b, "export type Lang = %s;\n\n", strings.Join(quoted, " | "))
	b.WriteString(`/** The form of a counted noun. A language with no rule of its own gets the
 * English one/other shape out of one and many. */
export function plural(lang: Lang, n: number, one: string, few: string, many: string): string {
  const abs = Math.abs(n);
  if (lang === "ru") {
    const rest = abs % 100;
    if (rest >= 11 && rest <= 14) return many;
    const last = abs % 10;
    if (last === 1) return one;
    if (last >= 2 && last <= 4) return few;
    return many;
  }
  return abs === 1 ? one : many;
}
`)
	return []byte(b.String())
}

func emitTSTypes(ref *catalog) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, tsHeader, "*")
	b.WriteString("/** One language's Catalog: a key per Surface, a nested object per group,\n" +
		" * a function per string. */\nexport type Strings = {\n")
	for _, s := range ref.surfaces {
		fmt.Fprintf(&b, "  %s: {\n", camel(s.name))
		for _, f := range surfaceFields(s) {
			if f.group == nil {
				fmt.Fprintf(&b, "    %s: %s => string;\n", camel(f.name), tsSignature(f.str))
				continue
			}
			fmt.Fprintf(&b, "    %s: {\n", camel(f.name))
			for _, e := range f.group.strings {
				fmt.Fprintf(&b, "      %s: %s => string;\n", camel(e.key), tsSignature(e))
			}
			b.WriteString("    };\n")
		}
		b.WriteString("  };\n")
	}
	b.WriteString("};\n")
	return []byte(b.String())
}

func emitTSCatalog(c *catalog) []byte {
	var body strings.Builder
	fmt.Fprintf(&body, "export const %s: Strings = {\n", varName(c.lang))
	for _, s := range c.surfaces {
		fmt.Fprintf(&body, "  %s: {\n", camel(s.name))
		for _, f := range surfaceFields(s) {
			if f.group == nil {
				fmt.Fprintf(&body, "    %s: %s,\n", camel(f.name), tsFunc(c.lang, f.str))
				continue
			}
			fmt.Fprintf(&body, "    %s: {\n", camel(f.name))
			for _, e := range f.group.strings {
				fmt.Fprintf(&body, "      %s: %s,\n", camel(e.key), tsFunc(c.lang, e))
			}
			body.WriteString("    },\n")
		}
		body.WriteString("  },\n")
	}
	body.WriteString("};\n\nexport default " + varName(c.lang) + ";\n")

	var b strings.Builder
	fmt.Fprintf(&b, tsHeader, c.lang)
	text := body.String()
	if strings.Contains(text, "plural(") {
		b.WriteString("import { plural } from \"./i18nstrings_plural_gen.js\";\n")
	}
	b.WriteString("import type { Strings } from \"./i18nstrings_types_gen.js\";\n\n")
	b.WriteString(text)
	return []byte(b.String())
}

func tsFunc(lang string, e *str) string {
	if len(e.params) == 0 {
		return "() => " + jsonString(literal(e))
	}
	var body strings.Builder
	for _, c := range e.chunks {
		switch c.kind {
		case chunkText:
			body.WriteString(backtick(c.text))
		case chunkField:
			fmt.Fprintf(&body, "${%s}", c.param)
		case chunkPlural:
			fmt.Fprintf(&body, "${plural(%s, %s, %s, %s, %s)}", jsonString(lang), c.param,
				jsonString(c.forms[0]), jsonString(c.forms[1]), jsonString(c.forms[2]))
		}
	}
	return tsSignature(e) + " => `" + body.String() + "`"
}

func tsSignature(e *str) string {
	var parts []string
	for _, p := range e.params {
		kind := "string"
		if p.isInt {
			kind = "number"
		}
		parts = append(parts, p.name+": "+kind)
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func literal(e *str) string {
	var b strings.Builder
	for _, c := range e.chunks {
		b.WriteString(c.text)
	}
	return b.String()
}

func backtick(text string) string {
	r := strings.NewReplacer(`\`, `\\`, "`", "\\`", "${", "\\${")
	return r.Replace(text)
}

func jsonString(s string) string {
	var b strings.Builder
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(s); err != nil {
		panic(err)
	}
	return strings.TrimRight(b.String(), "\n")
}
