#!/usr/bin/env python3
"""Rebuild web/ts/towns.ts: the ЧГК town list, each with its IANA timezone.

Two sources, joined on the Cyrillic name:
  - api.rating.chgk.net/towns — WHICH towns matter to ЧГК. Carries no timezone.
  - GeoNames cities500 — the timezone, plus Cyrillic alternate names to join on.

Both are fetched here, at build time, because the app's CSP forbids reaching
either at runtime. A town GeoNames doesn't know keeps its name and no zone: the
picker still offers it, the user picks the zone themselves.

    uv run python scripts/fetch_towns.py
"""

import csv
import io
import json
import pathlib
import sys
import urllib.request
import zipfile

RATING = "https://api.rating.chgk.net/towns?itemsPerPage=100&page={}"
GEONAMES = "https://download.geonames.org/export/dump/cities500.zip"
OUT = pathlib.Path(__file__).resolve().parent.parent / "web" / "ts" / "towns.ts"


def rating_towns() -> list[str]:
    names, page = [], 1
    while page <= 60:
        with urllib.request.urlopen(RATING.format(page), timeout=60) as r:
            batch = json.load(r)
        if not batch:
            break
        names += [(t.get("name") or "").strip() for t in batch]
        page += 1
    return sorted({n for n in names if n})


def geonames_zones() -> dict[str, str]:
    """name → timezone, keeping the most populous claimant of a shared name."""
    with urllib.request.urlopen(GEONAMES, timeout=300) as r:
        blob = r.read()
    zones: dict[str, tuple[str, int]] = {}
    with zipfile.ZipFile(io.BytesIO(blob)) as z:
        with z.open("cities500.txt") as f:
            text = io.TextIOWrapper(f, encoding="utf-8")
            for row in csv.reader(text, delimiter="\t", quoting=csv.QUOTE_NONE):
                if len(row) < 18 or not row[17]:
                    continue
                try:
                    pop = int(row[14] or 0)
                except ValueError:
                    pop = 0
                for name in [row[1], row[2]] + row[3].split(","):
                    name = name.strip()
                    if not name:
                        continue
                    prev = zones.get(name)
                    if prev is None or pop > prev[1]:
                        zones[name] = (row[17], pop)
    return {k: v[0] for k, v in zones.items()}


def main() -> int:
    names = rating_towns()
    zones = geonames_zones()
    towns = [{"name": n, **({"zone": zones[n]} if n in zones else {})} for n in names]
    matched = sum(1 for t in towns if "zone" in t)
    body = ",\n  ".join(json.dumps(t, ensure_ascii=False) for t in towns)
    OUT.write_text(
        "// Generated by scripts/fetch_towns.py — do not edit by hand.\n"
        "//\n"
        "// ЧГК's towns (api.rating.chgk.net) joined to their IANA timezone via\n"
        "// GeoNames. Bundled rather than fetched because the CSP forbids reaching\n"
        "// either source at runtime. A town with no `zone` is one GeoNames does not\n"
        f"// know; the picker still offers it. {matched} of {len(towns)} carry a zone.\n"
        "export interface Town { name: string; zone?: string }\n"
        f"export const TOWNS: Town[] = [\n  {body},\n];\n",
        encoding="utf-8",
    )
    print(f"{OUT}: {len(towns)} towns, {matched} with a zone")
    return 0


if __name__ == "__main__":
    sys.exit(main())
