// Code generated by scripts/i18nstringsgen from i18nstrings/en/*.toml. DO NOT EDIT.

package i18nstrings

import (
	"fmt"
)

// EN is the en Catalog.
var EN = Strings{
	Admin: AdminStrings{
		CreateUsers: AdminCreateUsersStrings{
			Name:  func() string { return "Create users" },
			Title: func() string { return "Create users — Spliff" },
		},
		Page: AdminPageStrings{
			Title: func() string { return "Admin" },
		},
	},
	Auth: AuthStrings{
		Login: AuthLoginStrings{
			FieldsRequired: func() string { return "Enter a username and a password." },
			Invalid:        func() string { return "Wrong username or password." },
		},
		Page: AuthPageStrings{
			Title: func() string { return "Log in to Spliff" },
		},
		Tg: AuthTgStrings{
			CodeMissing:   func() string { return "That code is not waiting for anyone. Start again." },
			NotConfigured: func() string { return "Telegram login is not set up on this instance." },
			TelegramTaken: func() string { return "That Telegram account is already linked to another user." },
		},
		Username: AuthUsernameStrings{
			Format:   func() string { return "A username is 3–64 characters of letters, digits and . _ -" },
			Reserved: func() string { return "That username is taken." },
		},
	},
	Bot: BotStrings{
		Login: BotLoginStrings{
			Hint: func(url string) string {
				return fmt.Sprintf("Open %s and press \"Log in with Telegram\" — the page will show you a code to send me.", url)
			},
		},
		Register: BotRegisterStrings{
			Done:    func() string { return "Done. Go back to the page you started from — you are logged in." },
			Expired: func() string { return "That code has expired. Open the login page again for a fresh one." },
		},
		Texts: BotTextsStrings{
			Down: func() string { return "Spliff is not answering right now. Try again in a minute." },
			Help: func() string { return "Send me the code the login page showed you, and I will log you in." },
		},
	},
	Common: CommonStrings{
		Cancel: func() string { return "Cancel" },
		Save:   func() string { return "Save" },
	},
	Group: GroupStrings{
		Error: GroupErrorStrings{
			CurrencyUnknown: func() string { return "We have no exchange rate for that currency." },
			NameRequired:    func() string { return "Give the group a name." },
			NameTooLong:     func() string { return "That name is too long." },
			NotAMember:      func() string { return "That person is not a member of this group." },
			NotSettled: func(name string, amount string) string {
				return fmt.Sprintf("%s is not settled up yet: %s.", name, amount)
			},
			OwnerMustHandOver:   func() string { return "Hand the group to somebody else first." },
			OwnerOnly:           func() string { return "Only the group's owner can do that." },
			PhantomNameRequired: func() string { return "Give the phantom a name." },
			PhantomNameTooLong:  func() string { return "That name is too long." },
			StillNamed:          func(name string) string { return fmt.Sprintf("%s is still named on a live transaction.", name) },
		},
	},
	Invite: InviteStrings{
		Error: InviteErrorStrings{
			AlreadyAMember: func() string { return "You are already in this group, so there is nobody to become." },
			ClaimNeedsDirectLink: func() string {
				return "This link waits for the owner's approval, so it cannot hand you a phantom. Ask for a direct link."
			},
			DecisionInvalid:  func() string { return "Approve or decline — there is no third answer." },
			LabelTooLong:     func() string { return "That label is too long." },
			LimitsOutOfRange: func() string { return "Check the number of uses and the expiry." },
			NoSeatsLeft:      func() string { return "That link has no seats left. Mint another one." },
			NotAPhantom:      func() string { return "That is not a phantom of this group." },
			NotFound:         func() string { return "There is no such invite link." },
			RequestNotFound:  func() string { return "There is no join request waiting from that person." },
		},
		Refusal: InviteRefusalStrings{
			Declined:  func() string { return "You were declined from this group through this link." },
			Exhausted: func() string { return "That link has been used up." },
			Expired:   func() string { return "That link has expired." },
			Generic:   func() string { return "That link does not work any more." },
			Revoked:   func() string { return "That link has been revoked." },
			Spent:     func() string { return "You already used that link once. Ask for a new one." },
		},
	},
	Notify: NotifyStrings{
		Involved: NotifyInvolvedStrings{
			Created: func(group string, description string, link string) string {
				return fmt.Sprintf("%s: \"%s\" was added, and it names you. %s", group, description, link)
			},
			Edited: func(group string, description string, link string) string {
				return fmt.Sprintf("%s: \"%s\" was changed, and it names you. %s", group, description, link)
			},
		},
		Join: NotifyJoinStrings{
			Text: func(name string, group string, link string) string {
				return fmt.Sprintf("%s wants to join %s. Approve or decline: %s", name, group, link)
			},
		},
		Unclaimed: NotifyUnclaimedStrings{
			Text: func(group string, description string, link string) string {
				return fmt.Sprintf("New in %s: \"%s\". Part of it is unclaimed — claim your share: %s", group, description, link)
			},
		},
	},
	Page: PageStrings{
		Common: PageCommonStrings{
			Home: func() string { return "Groups" },
		},
		Group: PageGroupStrings{
			Add:              func() string { return "Add a bill" },
			AddPhantom:       func() string { return "Add a phantom" },
			AddPhantomSubmit: func() string { return "Add them" },
			Balances:         func() string { return "Balances" },
			ConfirmDelete:    func() string { return "Delete this group and everything in it? This cannot be undone." },
			ConfirmKick:      func(name string) string { return fmt.Sprintf("Remove %s from the group?", name) },
			ConfirmLeave:     func() string { return "Leave this group?" },
			CurrencyLabel:    func() string { return "Base currency" },
			Debts:            func() string { return "Who pays whom" },
			Delete:           func() string { return "Delete the group" },
			Deleted:          func() string { return "Deleted transactions" },
			HandOver:         func() string { return "Hand over" },
			HandOverLabel:    func() string { return "Hand the group to" },
			History:          func() string { return "History" },
			Invites:          func() string { return "Invite links" },
			Kick:             func() string { return "Remove" },
			Leave:            func() string { return "Leave the group" },
			Members:          func() string { return "Members" },
			NameLabel:        func() string { return "Name" },
			NewInvite:        func() string { return "New invite link" },
			NoRates:          func() string { return "No exchange rates have been fetched yet, so balances are not stated." },
			NoTransactions:   func() string { return "Nothing has been added yet." },
			OwnerTag:         func() string { return "owner" },
			PhantomHint: func() string {
				return "Somebody at the table who is not on Spliff. They pay and hold shares like anybody; when they join through an invite link they can say \"I am Nino\" and take it all over."
			},
			PhantomNameLabel:       func() string { return "Their name" },
			PhantomNamePlaceholder: func() string { return "Nino" },
			PhantomTag:             func() string { return "phantom" },
			Settings:               func() string { return "Group settings" },
			Settled:                func() string { return "Everybody is settled up." },
			Title:                  func() string { return "Group" },
			Transactions:           func() string { return "Transactions" },
			Transfer:               func(from string, to string) string { return fmt.Sprintf("%s pays %s", from, to) },
			Unclaimed:              func(amount string) string { return fmt.Sprintf("%s unclaimed", amount) },
			You:                    func() string { return "you" },
		},
		History: PageHistoryStrings{
			Created:          func() string { return "added it" },
			Deleted:          func() string { return "deleted it" },
			Edited:           func() string { return "changed it" },
			FieldDay:         func(before string, after string) string { return fmt.Sprintf("date: %s → %s", before, after) },
			FieldDescription: func(before string, after string) string { return fmt.Sprintf("what for: %s → %s", before, after) },
			FieldTotal:       func(before string, after string) string { return fmt.Sprintf("total: %s → %s", before, after) },
			FieldUnclaimed:   func(before string, after string) string { return fmt.Sprintf("unclaimed: %s → %s", before, after) },
			PhotoAdded:       func() string { return "attached a photo" },
			PhotoRemoved:     func() string { return "removed a photo" },
			Restored:         func() string { return "restored it" },
			Somebody:         func() string { return "Somebody" },
		},
		Index: PageIndexStrings{
			CreateSubmit:    func() string { return "Create" },
			CreateTitle:     func() string { return "New group" },
			CurrencyLabel:   func() string { return "Base currency" },
			Empty:           func() string { return "No groups yet. Make one and invite the people you share expenses with." },
			Heading:         func() string { return "Your groups" },
			NameLabel:       func() string { return "Name" },
			NamePlaceholder: func() string { return "Tbilisi, October" },
			NewGroup:        func() string { return "New group" },
			Settled:         func() string { return "settled up" },
			Title:           func() string { return "Spliff" },
		},
		Invite: PageInviteStrings{
			Approval:         func() string { return "Hold joiners for my approval" },
			Approve:          func() string { return "Approve" },
			Copied:           func() string { return "Copied" },
			Copy:             func() string { return "Copy" },
			Decline:          func() string { return "Decline" },
			LabelLabel:       func() string { return "Label" },
			LabelPlaceholder: func() string { return "for the October trip" },
			MaxUsesLabel:     func() string { return "Uses (0 = unlimited)" },
			Mint:             func() string { return "Mint the link" },
			Remove:           func() string { return "Delete" },
			Revoke:           func() string { return "Revoke" },
			StateActive:      func() string { return "active" },
			StateExhausted:   func() string { return "used up" },
			StateExpired:     func() string { return "expired" },
			StateRevoked:     func() string { return "revoked" },
			TtlLabel:         func() string { return "Expires in hours (0 = never)" },
			Waiting:          func() string { return "waiting" },
		},
		Join: PageJoinStrings{
			AlreadyMember: func() string { return "You are already in this group." },
			Anonymous:     func() string { return "Log in and you will come straight back here." },
			AsYourself:    func() string { return "Join as yourself" },
			Dead:          func() string { return "This link does not work any more. Ask for a new one." },
			IAm:           func(name string) string { return fmt.Sprintf("I am %s", name) },
			Invited:       func() string { return "You have been invited. One tap and you are in." },
			Join:          func() string { return "Join the group" },
			Login:         func() string { return "Log in to join" },
			NeedsApproval: func() string { return "You have been invited. The owner approves joiners, so you will wait a moment." },
			Open:          func() string { return "Open the group" },
			Pending:       func() string { return "Your request is waiting for the owner." },
			PickWho: func() string {
				return "Somebody at this table is already in the group under a name. If one of them is you, say so and everything they paid and owe becomes yours."
			},
			Title:   func() string { return "Invitation" },
			Unnamed: func() string { return "A group on Spliff" },
		},
		Transaction: PageTransactionStrings{
			ColPaid:                func() string { return "Paid" },
			ColPercent:             func() string { return "Percent" },
			ColShare:               func() string { return "Share" },
			ConfirmDelete:          func() string { return "Delete this transaction? It stays in the history and can be restored." },
			ConfirmRemovePhoto:     func() string { return "Remove this photo?" },
			Currency:               func() string { return "Currency" },
			Day:                    func() string { return "Date" },
			Delete:                 func() string { return "Delete" },
			Description:            func() string { return "What for" },
			DescriptionPlaceholder: func() string { return "Dinner at Shavi Lomi" },
			ForWhom:                func() string { return "For whom" },
			FullyClaimed:           func() string { return "Every part of it is claimed." },
			HintClaim:              func() string { return "You paid and set your own share; the rest waits for the others to claim it." },
			HintEven: func() string {
				return "Everybody ticked splits it equally. The odd minor units go to whoever paid most."
			},
			HintExact: func() string { return "Type each person's share. What is left over stays unclaimed." },
			HintPercent: func() string {
				return "Give each person a percentage. They need not add up to 100 — what is left stays unclaimed."
			},
			HintSettlement:    func() string { return "Cash changed hands: the payer settles up with the person they paid." },
			HintSimple:        func() string { return "One person paid, and one person answers for the whole of it." },
			History:           func() string { return "History" },
			Mode:              func() string { return "How to split it" },
			ModeClaim:         func() string { return "I paid — claim your part" },
			ModeEven:          func() string { return "Split evenly" },
			ModeExact:         func() string { return "Exact amounts" },
			ModePercent:       func() string { return "Split by percent" },
			ModeSettlement:    func() string { return "Settling up" },
			ModeSimple:        func() string { return "A paid for B" },
			NeedMembers:       func() string { return "Tick at least one person." },
			NeedPayee:         func() string { return "Say who the money is for." },
			NeedPayer:         func() string { return "Say who paid." },
			NeedPaymentsMatch: func() string { return "The payments have to add up to the total." },
			NeedPercents:      func() string { return "Check the percentages." },
			NeedSharesFit:     func() string { return "The shares add up to more than the total." },
			NewTitle:          func() string { return "New transaction" },
			NoPhotos:          func() string { return "No photos yet." },
			PaidDone:          func() string { return "The payments add up to the total." },
			PaidLeft:          func(amount string) string { return fmt.Sprintf("%s of the total has no payer yet", amount) },
			PaidOver:          func(amount string) string { return fmt.Sprintf("The payments are %s more than the total", amount) },
			PhotoAlt:          func() string { return "Photo attached to this transaction" },
			Photos:            func() string { return "Photos" },
			PickPhoto:         func() string { return "Pick a picture first." },
			RateAsOf:          func(day string) string { return fmt.Sprintf("rate as of %s", day) },
			RemovePhoto:       func() string { return "Remove this photo" },
			Restore:           func() string { return "Restore" },
			Title:             func() string { return "Transaction" },
			Total:             func() string { return "Total" },
			UnclaimedNote:     func(amount string) string { return fmt.Sprintf("%s still unclaimed", amount) },
			Upload:            func() string { return "Attach a photo" },
			WhoPaid:           func() string { return "Who paid" },
		},
	},
	Profile: ProfileStrings{
		Logout: func() string { return "Log out" },
		Password: ProfilePasswordStrings{
			Current:      func() string { return "Current password (if set)" },
			CurrentWrong: func() string { return "That is not your current password." },
			Hint: func() string {
				return "A password is 8 to 72 characters long. Changing it logs out every other browser you are signed in on."
			},
			Length:   func() string { return "A password is 8 to 72 characters long." },
			Mismatch: func() string { return "The two new passwords do not match." },
			New:      func() string { return "New password" },
			Repeat:   func() string { return "Repeat the new password" },
			Saved:    func() string { return "Password saved. Every other session has been logged out." },
			Submit:   func() string { return "Save the password" },
			Title:    func() string { return "Change password" },
		},
		Telegram: ProfileTelegramStrings{
			AccountTaken: func() string { return "This account already has a Telegram account linked." },
			BotLead:      func() string { return "If the link does not open, write to the bot " },
			BotMid:       func() string { return " and send it this code:" },
			Expired:      func() string { return "The code has expired. Start again." },
			Hint:         func() string { return "Link a Telegram account and you can log in with it instead of the password." },
			LinkHint:     func() string { return "Follow this link to link your account:" },
			Linked:       func() string { return "Telegram linked." },
			LinkedLead:   func() string { return "Telegram: " },
			LinkedTail:   func() string { return "." },
			None:         func() string { return "No Telegram account is linked." },
			Start:        func() string { return "Link Telegram" },
			TimedOut:     func() string { return "The wait ran out. Reload the page." },
			Title:        func() string { return "Link Telegram" },
			Waiting:      func() string { return "Waiting for the bot to confirm…" },
		},
		Title: func() string { return "Your account" },
		Whoami: ProfileWhoamiStrings{
			Lead: func() string { return "You are logged in as " },
			Tail: func() string { return "." },
		},
	},
	Server: ServerStrings{
		Error: ServerErrorStrings{
			BadRequest: func() string { return "That request did not make sense." },
			Internal:   func() string { return "Something went wrong on our side. Try again." },
			NotFound:   func() string { return "Not found." },
		},
	},
	Transaction: TransactionStrings{
		Error: TransactionErrorStrings{
			CurrencyInvalid:     func() string { return "Pick a currency." },
			DayInvalid:          func() string { return "Pick a date." },
			Deleted:             func() string { return "That transaction is deleted. Restore it before editing it." },
			DescriptionRequired: func() string { return "Say what the money was for." },
			DescriptionTooLong:  func() string { return "That description is too long." },
			DuplicateMember:     func() string { return "Somebody is listed twice." },
			NegativeAmount:      func() string { return "Amounts cannot be negative." },
			NotAMember:          func() string { return "That person is not a member of this group." },
			PaymentRequired:     func() string { return "Say who paid." },
			PaymentsMismatch: func(paid string, total string) string {
				return fmt.Sprintf("The payments add up to %s, not %s.", paid, total)
			},
			PhotoMissing:    func() string { return "Pick a picture to attach." },
			PhotoNotAnImage: func() string { return "That file is not a picture." },
			PhotoTooLarge:   func() string { return "That picture is too big — 15 MB is the limit." },
			SharesOverdraw:  func(over string) string { return fmt.Sprintf("The shares are %s more than the total.", over) },
			TotalPositive:   func() string { return "The total has to be more than nothing." },
		},
	},
}
