// Code generated by internal/chgk/fsource/genmarkers from fsource.markerMapping. DO NOT EDIT.

// The 4s line markers and the element type each opens, longest first — the
// same table fsource.Parse reads by, so the browser's reader and the server's
// agree on what a marked line is.
export const MARKERS = [
  ["#EDITOR", "editor"],
  ["###LJ", "ljheading"],
  ["#DATE", "date"],
  ["###", "heading"],
  ["!=", "nezachet"],
  ["##", "section"],
  ["#B", "battle"],
  ["#R", "round"],
  ["#T", "theme"],
  ["№№", "setcounter"],
  ["!", "answer"],
  ["#", "meta"],
  ["/", "comment"],
  ["=", "zachet"],
  [">", "handout"],
  ["?", "question"],
  ["@", "author"],
  ["^", "source"],
  ["№", "number"],
] as const;

export type MarkerType = (typeof MARKERS)[number][1];
