// Code generated by cmd/palettegen. DO NOT EDIT.
// Source: dopeuikit/palette/sets.json + uchu.json.

/** The label colour set, in offer order. These are NAMES: the hex a name
 * paints is --label-<name>, and differs per theme. */
export const LABEL_COLORS: readonly string[] = [
  "red",
  "orange",
  "brown",
  "yellow",
  "lime",
  "green",
  "teal",
  "cyan",
  "blue",
  "purple",
  "magenta",
  "pink",
  "gray",
  "red-deep",
  "orange-deep",
  "brown-deep",
  "yellow-deep",
  "lime-deep",
  "green-deep",
  "teal-deep",
  "cyan-deep",
  "blue-deep",
  "purple-deep",
  "magenta-deep",
  "pink-deep",
];

/** Hex → name for labels stored before the palette was named. */
export const LEGACY_LABEL_HEX: Readonly<Record<string, string>> = {
  "#a84151": "red",
  "#d69870": "orange",
  "#ebd697": "yellow",
  "#77bb79": "green",
  "#3d64ac": "blue",
  "#674292": "purple",
  "#e5b5c7": "pink",
  "#bfc1c3": "gray",
};

/** Each label name on the OKLab a/b plane, for snapping a stray hex. */
export const LABEL_AB: Readonly<Record<string, readonly [number, number]>> = {
  "red": [0.2176, 0.0775],
  "orange": [0.0872, 0.1120],
  "brown": [0.0383, 0.0490],
  "yellow": [-0.0032, 0.0969],
  "lime": [-0.0628, 0.1178],
  "green": [-0.1295, 0.0905],
  "teal": [-0.1126, 0.0102],
  "cyan": [-0.0918, -0.0621],
  "blue": [-0.0373, -0.2188],
  "purple": [0.1020, -0.1893],
  "magenta": [0.1368, -0.0895],
  "pink": [0.0835, -0.0089],
  "gray": [-0.0031, -0.0025],
};

/** uchu's ink — the dark end every rung was balanced against. */
export const YIN = "#080a0d";

/** uchu's paper. */
export const YANG = "#fdfdfd";
