// Code generated by cmd/palettegen. DO NOT EDIT.
// Source: dopeuikit/palette/sets.json + uchu.json.

/** The label colour set, in offer order. */
export const LABEL_COLORS: readonly string[] = [
  "#a84151",
  "#d69870",
  "#ebd697",
  "#77bb79",
  "#3d64ac",
  "#674292",
  "#e5b5c7",
  "#bfc1c3",
];

/** uchu's ink — the dark end every rung was balanced against. */
export const YIN = "#080a0d";

/** uchu's paper. */
export const YANG = "#fdfdfd";
